// chplcgtypes.h
//
// Verbatim copies of types generated by the compiler from module code 
// which are needed by the runtime.
//
// The C compiler complains if these appear more than once in a compilation, so
// this file must not be included when compiling the generated C code.
//

#ifdef chplcgtypes_h
#error Multiple inclusion
#else
#define chplcgtypes_h

// Copied verbatim from chpl__header.h.
typedef struct chpl_chpl_localeID_t_s {
  int32_t node;
  int32_t subloc;
} chpl_localeID_t;

#endif
