
include src/qio/regexp/$(CHPL_MAKE_REGEXP)/Makefile.include
include src/qio/auxFilesys/$(CHPL_MAKE_AUXFS)/Makefile.include

QIO_OBJDIR = $(RUNTIME_ROOT)/$(COMMON_SUBDIR)/qio/$(RUNTIME_OBJDIR)

ALL_SRCS += $(CURDIR)/$(COMMON_SUBDIR)/qio/*.c

include $(RUNTIME_ROOT)/$(COMMON_SUBDIR)/qio/Makefile.share
