#!/usr/bin/env perl
#
# Sort lines starting with "CHPL TEST"
#

$file = $ARGV[0];
system("mv $file.exec.out.tmp $file.tmp");
open(INFILE, "<$file.tmp");
open(OUTFILE, ">$file.exec.out.tmp");

while ($line = <INFILE>) {
    if ($line =~ m/^CHPL TEST/) {
        push(@testLines, $line);
    } else {
        printTestLines();
    }
}
printTestLines();

close(OUTFILE);
close(INFILE);
system("rm $file.tmp");

sub printTestLines() {
    if ($#testLines >= 0) {
        @sortedTestLines = sort @testLines;
        foreach $testLine (@sortedTestLines) {
            print OUTFILE $testLine;
        }
        @testLines = ();
    }
    print OUTFILE $line;
}
