#!/usr/bin/perl
#
# by default: run tests on release/examples directory with
#             combinations of optimization flags listed in
#             OPT_TESTING_FLAGS
#
# -cron: check out a new copy of chapel, make it, run tests as above,
#        and mail results to chapel_cronmail@cray.com
#

if (@ARGV) {
    $flag = shift @ARGV;
    if ($flag eq "--cron" || $flag eq "-cron") {
        $cron = 1;
    } else {
        die "usage: start_opt_test [--cron]\n";
    }
}

if ($cron) {
    `rm -rf /tmp/opt_testing`;
    `mkdir /tmp/opt_testing`;
    `cd /tmp/opt_testing && cvs checkout nightly >& /dev/null`;
    `cd /tmp/opt_testing/chapel && make all >& /dev/null`;
    $home = "/tmp/opt_testing/chapel/test";
} else {
    $home = ".";
}

@OPTS = `cat $home/OPT_TESTING_FLAGS`;

`rm -f .opt_testing.tmp`;

foreach $opt (@OPTS) {
    chomp $opt;
    system("echo \"\" | tee -a $home/.opt_testing.tmp");
    system("echo \"OPTIMIZATION FLAGS: $opt\" | tee -a $home/.opt_testing.tmp");
    system("echo \"\" | tee -a $home/.opt_testing.tmp");
    system("cd $home && start_test release/examples --compopts \"$opt\" | tee -a .opt_testing.tmp");
}

@lines = `cat $home/.opt_testing.tmp`;

foreach $line (@lines) {
    if ($line =~ /\[Error/) {
        $nerrort2++;
    }
}

if ($cron) {
    $nerror = $nerrort2/2;
    open(FILE, "| mail -s \"Chapel Opts Nightly: $nerror errors\" chapel_cronmail\@cray.com");
} else {
    open(FILE, ">&STDOUT");
}

$nerror = 0;
$first = 1;
foreach $line (@lines) {
    chomp $line;
    if ($line =~ /OPTIMIZATION\ FLAGS\:\ (.*)/) {
        print FILE "$1\n";
    } elsif ($line =~ /\[Test Summary/) {
        print FILE "\n";
        $show = 1;
    } elsif ($line =~ /\[END/) {
        print FILE "\n";
        $show = 0;
    } elsif ($show) {
        if ($line =~ /\[Error/) {
            $nerror++;
        }
        print FILE "$line\n";
    }
}

print FILE "Total Errors: $nerror\n";

if ($cron) {
    close(FILE);
}
