// Generated by clang_builtin_gen.py based on clang's Builtins.def
static inline double cimag(_Complex double arg0)
{
  return __builtin_cimag(arg0);
}

static inline _Complex double conj(_Complex double arg0)
{
  return __builtin_conj(arg0);
}

static inline double creal(_Complex double arg0)
{
  return __builtin_creal(arg0);
}

static inline float crealf(_Complex float arg0)
{
  return __builtin_crealf(arg0);
}

static inline long double creall(_Complex long double arg0)
{
  return __builtin_creall(arg0);
}

static inline float cimagf(_Complex float arg0)
{
  return __builtin_cimagf(arg0);
}

static inline long double cimagl(_Complex long double arg0)
{
  return __builtin_cimagl(arg0);
}

static inline _Complex long double conjl(_Complex long double arg0)
{
  return __builtin_conjl(arg0);
}

static inline _Complex float conjf(_Complex float arg0)
{
  return __builtin_conjf(arg0);
}

