.TH HPL_pnum 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_pnum \- Rank determination.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&int\fR
\fB\&HPL_pnum(\fR
\fB\&const HPL_T_grid *\fR
\fI\&GRID\fR,
\fB\&const int\fR
\fI\&MYROW\fR,
\fB\&const int\fR
\fI\&MYCOL\fR
\fB\&);\fR
.SH DESCRIPTION
\fB\&HPL_pnum\fR
determines  the  rank  of a  process  as a function  of  its
coordinates in the grid.
.SH ARGUMENTS
.TP 8
GRID    (local input)           const HPL_T_grid *
On entry,  GRID  points  to the data structure containing the
process grid information.
.TP 8
MYROW   (local input)           const int
On entry,  MYROW  specifies the row coordinate of the process
whose rank is to be determined. MYROW must be greater than or
equal to zero and less than NPROW.
.TP 8
MYCOL   (local input)           const int
On entry,  MYCOL  specifies  the  column  coordinate  of  the
process whose rank is to be determined. MYCOL must be greater
than or equal to zero and less than NPCOL.
.SH SEE ALSO
.BR HPL_grid_init \ (3),
.BR HPL_grid_info \ (3),
.BR HPL_grid_exit \ (3).
