.TH main 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
main \- HPL main timing program.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&int\fR
\fB\&main();\fR
.SH DESCRIPTION
\fB\&main\fR
is the main driver program for testing the HPL routines.
This  program is  driven  by  a short data file named  "HPL.dat".
.SH SEE ALSO
.BR HPL_pdinfo \ (3),
.BR HPL_pdtest \ (3).
