.TH HPL_ladd 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_ladd \- Adds two long positive integers.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&void\fR
\fB\&HPL_ladd(\fR
\fB\&int *\fR
\fI\&J\fR,
\fB\&int *\fR
\fI\&K\fR,
\fB\&int *\fR
\fI\&I\fR
\fB\&);\fR
.SH DESCRIPTION
\fB\&HPL_ladd\fR
adds  without carry two long positive integers  K and J  an
put the result into I.  The long integers  I, J, K are encoded on 31
bits using an array of 2 integers.  The 16-lower bits  are stored  i
the  first  entry  of each array,  the 15-higher bits  in the second
entry.
.SH ARGUMENTS
.TP 8
J       (local input)           int *
On entry, J is an integer array of dimension 2 containing the
encoded long integer J.
.TP 8
K       (local input)           int *
On entry, K is an integer array of dimension 2 containing the
encoded long integer K.
.TP 8
I       (local output)          int *
On entry, I is an integer array of dimension 2. On exit, this
array contains the encoded long integer result.
.SH SEE ALSO
.BR HPL_lmul \ (3),
.BR HPL_setran \ (3),
.BR HPL_xjumpm \ (3),
.BR HPL_jumpit \ (3),
.BR HPL_rand \ (3).
