.TH HPL_dger 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_dger \- A := alpha * x * y^T + A.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&void\fR
\fB\&HPL_dger(\fR
\fB\&const enum HPL_ORDER\fR
\fI\&ORDER\fR,
\fB\&const int\fR
\fI\&M\fR,
\fB\&const int\fR
\fI\&N\fR,
\fB\&const double\fR
\fI\&ALPHA\fR,
\fB\&const double *\fR
\fI\&X\fR,
\fB\&const int\fR
\fI\&INCX\fR,
\fB\&double *\fR
\fI\&Y\fR,
\fB\&const int\fR
\fI\&INCY\fR,
\fB\&double *\fR
\fI\&A\fR,
\fB\&const int\fR
\fI\&LDA\fR
\fB\&);\fR
.SH DESCRIPTION
\fB\&HPL_dger\fR
performs the rank 1 operation
 
    A := alpha * x * y^T + A,
 
where alpha is a scalar,  x is an m-element vector, y is an n-element
vector and A is an m by n matrix.
.SH ARGUMENTS
.TP 8
ORDER   (local input)           const enum HPL_ORDER
On entry, ORDER  specifies the storage format of the operands
as follows:                                                  
   ORDER = HplRowMajor,                                      
   ORDER = HplColumnMajor.                                   
.TP 8
M       (local input)           const int
On entry,  M  specifies  the number of rows of  the matrix A.
M must be at least zero.
.TP 8
N       (local input)           const int
On entry, N  specifies the number of columns of the matrix A.
N must be at least zero.
.TP 8
ALPHA   (local input)           const double
On entry, ALPHA specifies the scalar alpha.   When  ALPHA  is
supplied as zero then  X and Y  need not be set on input.
.TP 8
X       (local input)           const double *
On entry,  X  is an incremented array of dimension  at  least
( 1 + ( m - 1 ) * abs( INCX ) )  that  contains the vector x.
.TP 8
INCX    (local input)           const int
On entry, INCX specifies the increment for the elements of X.
INCX must not be zero.
.TP 8
Y       (local input)           double *
On entry,  Y  is an incremented array of dimension  at  least
( 1 + ( n - 1 ) * abs( INCY ) )  that  contains the vector y.
.TP 8
INCY    (local input)           const int
On entry, INCY specifies the increment for the elements of Y.
INCY must not be zero.
.TP 8
A       (local input/output)    double *
On entry,  A  points  to an array of size equal to or greater
than LDA * n.  Before  entry, the leading m by n part  of the
array  A  must contain the matrix coefficients. On exit, A is
overwritten by the updated matrix.
.TP 8
LDA     (local input)           const int
On entry,  LDA  specifies  the  leading  dimension  of  A  as
declared  in  the  calling  (sub) program.  LDA  must  be  at
least MAX(1,m).
.SH EXAMPLE
\fI\&#include "hpl.h"\fR
 
int main(int argc, char *argv[])
.br
{
.br
   double a[2*2], x[2], y[2];
.br
   a[0] = 1.0; a[1] = 2.0; a[2] = 3.0; a[3] = 3.0;
.br
   x[0] = 2.0; x[1] = 1.0; y[2] = 1.0; y[3] = 2.0;
.br
   HPL_dger( HplColumnMajor, 2, 2, 2.0, x, 1, y, 1,
.br
             a, 2 );
.br
   printf("y=[%f,%f]\en", y[0], y[1]);
.br
   exit(0); return(0);
.br
}
.SH SEE ALSO
.BR HPL_dgemv \ (3),
.BR HPL_dtrsv \ (3).
