.TH HPL_timer_walltime 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_timer_walltime \- Return the elapsed (wall-clock) time.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&double\fR
\fB\&HPL_timer_walltime();\fR
.SH DESCRIPTION
\fB\&HPL_timer_walltime\fR
returns the elapsed (wall-clock) time.
.SH SEE ALSO
.BR HPL_timer_cputime \ (3),
.BR HPL_timer \ (3).
