.TH HPL_ptimer_walltime 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_ptimer_walltime \- Return the elapsed (wall-clock) time.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&double\fR
\fB\&HPL_ptimer_walltime();\fR
.SH DESCRIPTION
\fB\&HPL_ptimer_walltime\fR
returns the elapsed (wall-clock) time.
.SH SEE ALSO
.BR HPL_ptimer_cputime \ (3),
.BR HPL_ptimer \ (3).
