.TH HPL_dlaswp06N 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_dlaswp06N \- swap rows of U with rows of A.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&void\fR
\fB\&HPL_dlaswp06N(\fR
\fB\&const int\fR
\fI\&M\fR,
\fB\&const int\fR
\fI\&N\fR,
\fB\&double *\fR
\fI\&A\fR,
\fB\&const int\fR
\fI\&LDA\fR,
\fB\&double *\fR
\fI\&U\fR,
\fB\&const int\fR
\fI\&LDU\fR,
\fB\&const int *\fR
\fI\&LINDXA\fR
\fB\&);\fR
.SH DESCRIPTION
\fB\&HPL_dlaswp06N\fR
swaps rows of  U  with rows of A at positions
indicated by LINDXA.
.SH ARGUMENTS
.TP 8
M       (local input)           const int
On entry, M  specifies the number of rows of A that should be
swapped with rows of U. M must be at least zero.
.TP 8
N       (local input)           const int
On entry, N specifies the length of the rows of A that should
be swapped with rows of U. N must be at least zero.
.TP 8
A       (local output)          double *
On entry, A points to an array of dimension (LDA,N). On exit,
the  rows of this array specified by  LINDXA  are replaced by
rows or columns of U.
.TP 8
LDA     (local input)           const int
On entry, LDA specifies the leading dimension of the array A.
LDA must be at least MAX(1,M).
.TP 8
U       (local input/output)    double *
On entry,  U  points  to an array of dimension (LDU,N).  This
array contains the rows of U that are to be swapped with rows
of A.
.TP 8
LDU     (local input)           const int
On entry, LDU specifies the leading dimension of the array U.
LDU must be at least MAX(1,M).
.TP 8
LINDXA  (local input)           const int *
On entry, LINDXA is an array of dimension M that contains the
local row indexes of A that should be swapped with U.
.SH SEE ALSO
.BR HPL_dlaswp00N \ (3),
.BR HPL_dlaswp10N \ (3),
.BR HPL_dlaswp01N \ (3),
.BR HPL_dlaswp01T \ (3),
.BR HPL_dlaswp02N \ (3),
.BR HPL_dlaswp03N \ (3),
.BR HPL_dlaswp03T \ (3),
.BR HPL_dlaswp04N \ (3),
.BR HPL_dlaswp04T \ (3),
.BR HPL_dlaswp05N \ (3),
.BR HPL_dlaswp05T \ (3),
.BR HPL_dlaswp06N \ (3),
.BR HPL_dlaswp06T \ (3).
