.TH HPL_pdpanel_disp 3 "January 20, 2004" "HPL 1.0a" "HPL Library Functions"
.SH NAME
HPL_pdpanel_disp \- Deallocate a panel data structure.
.SH SYNOPSIS
\fB\&#include "hpl.h"\fR
 
\fB\&int\fR
\fB\&HPL_pdpanel_disp(\fR
\fB\&HPL_T_panel * *\fR
\fI\&PANEL\fR
\fB\&);\fR
.SH DESCRIPTION
\fB\&HPL_pdpanel_disp\fR
deallocates  the  panel  structure  and  resources  and
stores the error code returned by the panel factorization.
.SH ARGUMENTS
.TP 8
PANEL   (local input/output)    HPL_T_panel * *
On entry,  PANEL  points  to  the  address  of the panel data
structure to be deallocated.
.SH SEE ALSO
.BR HPL_pdpanel_new \ (3),
.BR HPL_pdpanel_init \ (3),
.BR HPL_pdpanel_free \ (3).
