#!/usr/bin/env python3

import sys, string

# assumes format of of log file name is 'testname.#-0.exec.out.tmp'
testname = sys.argv[1]
execlog = sys.argv[2]

testnum = execlog[execlog.find('.')+1:execlog.find('-')]

f = open(testname+'.good', 'w');

if (execlog.find('configParam')==0 or
    execlog.find('configConst')==0 or
    execlog.find('configVar')==0):
    if testnum=='1':
        f.write('4\n');
    elif testnum=='2':
        f.write('-35\n');
    elif testnum=='3':
        f.write('blah blah blah\n');
    elif testnum=='4':
        f.write('65535\n');
    else:
        f.write('INVALID TEST\n');
else:
    if testnum=='1':
        f.write('18446744073709551615\n');
    elif testnum=='2':
        f.write('3.40282e+38\n');
    elif testnum=='3':
        f.write('1.79769e+308 + 1.79769e+308i\n');
    else:
        f.write('INVALID TEST\n');

f.close();

