/*
 * Copyright 2004-2019 Cray Inc.
 * Other additional copyright holders may be indicated within.
 *
 * The entirety of this work is licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "mli_common_code.c"
#include <time.h>

//
// Print a debug message, or do nothing if debug messages are turned off.
//
#ifdef CHPL_MLI_DEBUG_PRINT
# define chpl_mli_sdebugf(fmt, ...)               \
  do {                                            \
      printf("%s ", "[Server]");                  \
      printf(fmt, __VA_ARGS__);                   \
  } while (0)
#else
# define chpl_mli_sdebugf(fmt, ...)
#endif

//
// The definition of this is generated by the compiler.
//
int64_t chpl_mli_sdispatch(int64_t id);

//
// Contains sockets.
//
struct chpl_mli_context chpl_server;

void chpl_mli_server_init(struct chpl_mli_context* server) {
  if (server->context) { return; }

  server->context = zmq_ctx_new();
  server->setup_sock = zmq_socket(server->context, ZMQ_PUSH);
  server->main    = zmq_socket(server->context, ZMQ_REP);
  server->arg     = zmq_socket(server->context, ZMQ_REP);
  server->res     = zmq_socket(server->context, ZMQ_REQ);

  return;
}

void chpl_mli_server_deinit(struct chpl_mli_context* server) {
  if (!server->context) { return; }

  // TODO: Set socket LINGER to 0 to prevent blocking.
  zmq_ctx_destroy(server->context);
  server->context = NULL;

  return;
}

//
// TODO
// 
// Server takes no arguments for now to make dropping into it easier. Later,
// we may want to pass it argc/argv, which will make things a bit more
// complicated with regards to AST transformations. But for now, don't pass
// it anything.
//
void chpl_mli_smain(void) {
  int64_t id = -1;
  int64_t ack = 0;
  int execute = 1;
  int err = 0;
  clock_t before = clock();
  double seconds = 0;

  //
  // TODO: With proper server setup, these ports should no longer be fixed.
  // We should be able to eliminate the use of one port as well.
  // 
  const char* ip = "localhost";
  const char* setupPort = "5554";
  const char* mainport = "5555";
  const char* argport = "5556";
  const char* resport = "5557";

  chpl_mli_server_init(&chpl_server);

  chpl_mli_connect(chpl_server.setup_sock, ip, setupPort);
  chpl_mli_bind(chpl_server.main, ip, mainport);
  chpl_mli_bind(chpl_server.arg, ip, argport);
  chpl_mli_bind(chpl_server.res, ip, resport);

  chpl_mli_sdebugf("%s\n", "Starting server for multi-locale library!");
  chpl_mli_sdebugf("Main port on: %s, %s\n", ip, mainport);
  chpl_mli_sdebugf("Arg port on: %s, %s\n", ip, argport);
  chpl_mli_sdebugf("Res port on: %s, %s\n", ip, resport);

  while (execute) {

    chpl_mli_sdebugf("%s\n", "Listening...");
    
    // Every transaction starts by reading an int64 off the wire.
    err = chpl_mli_pull(
              chpl_server.main,
              &id,
              sizeof(id),
              0);

    // TODO: Handle socket errors on inbound read.
    if (err < 0) {
      chpl_mli_sdebugf("Socket error on read: %d\n", err);
      execute = 0;
      ack = CHPL_MLI_ERROR_SOCKET;
    }

    if (id < 0) {
      chpl_mli_sdebugf("Client sent error: %s\n", chpl_mli_errstr(id));
    } else {
      chpl_mli_sdebugf("Received request for ID: %lld\n", id);
    }
 
    // TODO: How to restructure the loop to reply with something meaningful?
    chpl_mli_sdebugf("Responding with error: %s\n", chpl_mli_errstr(0));
    err = chpl_mli_push(chpl_server.main, "", 0, 0);

    // TODO: Handle socket errors on outbound push.
    if (err < 0) { chpl_mli_sdebugf("Socket error on write: %d\n", err); }

    // For now, treat negative values of ID as shutdown code.
    if (execute && id < 0) {
      chpl_mli_sdebugf("Shutdown, code: %lld\n", id);
      execute = 0;
      ack = CHPL_MLI_ERROR_SHUTDOWN;
    }
   
    if (execute && id >= 0) {
      ack = chpl_mli_sdispatch(id);
    }
  }

  seconds = (double) (clock() - before) / (double) CLOCKS_PER_SEC;

  chpl_mli_server_deinit(&chpl_server);

  chpl_mli_sdebugf("Graceful shutdown, time elapsed: %gs\n", seconds);

  return;
}

