rules:
  unpinned-images:
    ignore:
      - arkouda-smoke-test.yml
      - core-ci-checks.yml
      - extended-ci-checks.yml
      - full-ci-checks.yml
      - ga-paratest.yml
  dangerous-triggers:
    ignore:
      - email.yml:2
