#ifndef _prim_data_H
#define _prim_data_H

void prim_init(Primitives *p, IF1 *if1);

extern Prim *prim_operator;
#define P_prim_operator 0
extern Prim *prim_period;
#define P_prim_period 1
extern Prim *prim_exp;
#define P_prim_exp 2
extern Prim *prim_mult;
#define P_prim_mult 3
extern Prim *prim_div;
#define P_prim_div 4
extern Prim *prim_mod;
#define P_prim_mod 5
extern Prim *prim_add;
#define P_prim_add 6
extern Prim *prim_subtract;
#define P_prim_subtract 7
extern Prim *prim_lsh;
#define P_prim_lsh 8
extern Prim *prim_rsh;
#define P_prim_rsh 9
extern Prim *prim_less;
#define P_prim_less 10
extern Prim *prim_lessorequal;
#define P_prim_lessorequal 11
extern Prim *prim_greater;
#define P_prim_greater 12
extern Prim *prim_greaterorequal;
#define P_prim_greaterorequal 13
extern Prim *prim_equal;
#define P_prim_equal 14
extern Prim *prim_notequal;
#define P_prim_notequal 15
extern Prim *prim_and;
#define P_prim_and 16
extern Prim *prim_xor;
#define P_prim_xor 17
extern Prim *prim_or;
#define P_prim_or 18
extern Prim *prim_land;
#define P_prim_land 19
extern Prim *prim_lor;
#define P_prim_lor 20
extern Prim *prim_assign;
#define P_prim_assign 21
extern Prim *prim_apply;
#define P_prim_apply 22
extern Prim *prim_by;
#define P_prim_by 23
extern Prim *prim_plus;
#define P_prim_plus 24
extern Prim *prim_minus;
#define P_prim_minus 25
extern Prim *prim_bnot;
#define P_prim_bnot 26
extern Prim *prim_not;
#define P_prim_not 27
extern Prim *prim_deref;
#define P_prim_deref 28
extern Prim *prim_ref;
#define P_prim_ref 29
extern Prim *prim_cast;
#define P_prim_cast 30
extern Prim *prim_sizeof;
#define P_prim_sizeof 31
extern Prim *prim_reply;
#define P_prim_reply 32
extern Prim *prim_tuple;
#define P_prim_tuple 33
extern Prim *prim_vector;
#define P_prim_vector 34
extern Prim *prim_continuation;
#define P_prim_continuation 35
extern Prim *prim_new;
#define P_prim_new 36
extern Prim *prim_index_object;
#define P_prim_index_object 37
extern Prim *prim_meta_apply;
#define P_prim_meta_apply 38
extern Prim *prim_destruct;
#define P_prim_destruct 39
extern Prim *prim_set;
#define P_prim_set 40
extern Prim *prim_list;
#define P_prim_list 41
extern Prim *prim_primitive;
#define P_prim_primitive 42
#endif
