MPI_INSTALL = $(CHAPEL_ROOT)/third-party/openmpi/install

RUNTIME_LFLAGS += -I$(MPI_INSTALL)/include -pthread -L$(MPI_INSTALL)/lib
GEN_LFLAGS += $(RUNTIME_LFLAGS)
LIBS += -lmpi -lopen-rte -lopen-pal -lrt -ldl -Wl,--export-dynamic -lnsl -lutil -lm -ldl
