MAIN_SRCS = \
	arg.cpp \
	driver.cpp \
	runpasses.cpp \
        runtime.cpp \
	version.cpp \

CVS_SRCS = $(MAIN_SRCS)
SRCS = $(CVS_SRCS)

MAIN_OBJS = \
	$(MAIN_SRCS:%.cpp=$(MAIN_OBJDIR)/%.$(OBJ_SUFFIX))
