PASSES_SRCS = \
	buildBinary.cpp \
	codegen.cpp \
	createEntryPoint.cpp \
	filesToAST.cpp \
	pass.cpp \
	preAnalysisCleanup.cpp \
	printProgram.cpp \
	renameCSymbols.cpp \
	runAnalysis.cpp \

CVS_SRCS = $(PASSES_SRCS)
SRCS = $(CVS_SRCS)

PASSES_OBJS = \
	$(PASSES_SRCS:%.cpp=$(PASSES_OBJDIR)/%.$(OBJ_SUFFIX))
