var a: real = -29.39;
var b: real = -31.87;
var c: real = 0;
var d: real = 0.1111;
var e: real = 1.1111;
var f: real = 99.99;

writeln("a = ", a);
writeln("ceil(a) = ", ceil(a));
writeln("b = ", b);
writeln("ceil(b) = ", ceil(b));
writeln("c = ", c);
writeln("ceil(c) = ", ceil(c));
writeln("d = ", d);
writeln("ceil(d) = ", ceil(d));
writeln("e = ", e);
writeln("ceil(e) = ", ceil(e));
writeln("f = ", f);
writeln("ceil(f) = ", ceil(f));
