# put Cray PE cross-compilation intel-specific settings here

# Warnings squashed for generated code
# 592 : squelch use-before-def problems -- we'll rely on valgrind to catch them
CRAYPE_GEN_CFLAGS = -wr592

include $(CHPL_MAKE_HOME)/make/compiler/Makefile.$(CHPL_MAKE_TARGET_PLATFORM)

RUNTIME_CFLAGS += -std=gnu99 -wr188
GEN_CFLAGS += -std=gnu99
