#
# Settings for the Cray XT3 and XT4
#

#
# tools
#

CC = cc
CXX = CC

MAKEDEPEND = $(CXX) -M
CMAKEDEPEND = $(CC) -M

RANLIB = ranlib


#
# flags
#

-include $(CHAPEL_ROOT)/make/compiler/Makefile.cc-cray-xt.$(PE_ENV)

DEBUG_CFLAGS = -g
OPT_CFLAGS = 

CFLAGS = -target=linux
LFLAGS = -target=linux
LDFLAGS= -target=linux

COMP_CFLAGS = $(CFLAGS)
RUNTIME_CFLAGS = $(CFLAGS)
GEN_CFLAGS = $(CFLAGS) $(XT_GEN_CFLAGS)
GEN_LFLAGS = $(LFLAGS)
