# Copyright 2004-2020 Hewlett Packard Enterprise Development LP
# Other additional copyright holders may be indicated within.
# 
# The entirety of this work is licensed under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# 
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Makefile: reports on the configured Chapel build
#

ifndef CHPL_MAKE_HOME
export CHPL_MAKE_HOME=$(realpath $(shell pwd)/..)
endif

include $(CHPL_MAKE_HOME)/make/Makefile.base

unexport CHPL_MAKE_CHPLENV_CACHE

# Set up variables representing paths that will be installed
ifndef CHPL_MAKE_RUNTIME_LIB
CHPL_MAKE_RUNTIME_LIB = $(CHPL_MAKE_HOME)/lib
endif

ifndef CHPL_MAKE_RUNTIME_INCL
CHPL_MAKE_RUNTIME_INCL = $(CHPL_MAKE_HOME)/runtime/include
endif

ifndef CHPL_MAKE_THIRD_PARTY
CHPL_MAKE_THIRD_PARTY = $(CHPL_MAKE_HOME)/third-party
endif

FIXPATH_CMD := $(CHPL_MAKE_HOME)/util/config/replace-paths.py \
                  --fixpath '$$CHPL_RUNTIME_LIB' $(CHPL_MAKE_RUNTIME_LIB) \
                  --fixpath '$$CHPL_RUNTIME_INCL' $(CHPL_MAKE_RUNTIME_INCL) \
                  --fixpath '$$CHPL_THIRD_PARTY' $(CHPL_MAKE_THIRD_PARTY) \
                  --fixpath '$$CHPL_HOME' $(CHPL_MAKE_HOME)

printincludesanddefines: FORCE
	@$(MAKE) --no-print-directory -f etc/Makefile.include printincludesanddefines | $(FIXPATH_CMD)

printlibraries: FORCE
	@$(MAKE) --no-print-directory -f etc/Makefile.include printlibraries | $(FIXPATH_CMD)

printoverrideld: FORCE
	@$(MAKE) --no-print-directory -f etc/Makefile.include printoverrideld | $(FIXPATH_CMD)

FORCE:

.NOTPARALLEL:
