name: GitHub Action Schedule

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
    nroff-elves-scheduled:
        name: The Nroff Elves
        runs-on: ubuntu-latest
        steps:
          - name: Debug information
            env:
              GITHUB_DATA: ${{ toJSON(github) }}
            run: |
              echo This is information that may be useful for debugging.
              echo "$GITHUB_DATA"

          - name: Check out the git repo
            uses: actions/checkout@v2

          - name: Get the required packages
            run: sudo apt install -y pandoc hub

          - name: Build the nroff man pages
            run: .github/workflows/nroff-elves.sh
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              REPO: ${{ github.event.repository.full_name }}
              BASE_REF: ${{ github.event.repository.default_branch }}
