// Verified the behavior of types with only secondary initializers when the
// initializer is defined in a module outside of the module where the type is
// originally defined.
module A {
  class Foo {
    var x: int;
    var y = false;
  }
}

module B {
  use A;

  proc Foo.init(xVal) {
    writeln("In secondary initializer of class Foo");
    x = xVal;
    y = xVal > 5;
  }

  proc main() {
    var f = new Foo(10);
    // Should use the secondary initializer defined in this module
    writeln(f); // expect 10, true

    // Should use the default initializer generated by the compiler
    var f2 = new Foo(2, true);
    writeln(f2);
  }
}
