#!/usr/bin/env bash


if [[ "$CHPL_COMM" != "none" || "$CHPL_RE2" == "none" || "$CHPL_LAUNCHER" != "none" ]]; then
  echo "True"
else
  if command -v chplcheck >/dev/null 2>&1; then
    echo "False"
  else
    echo "True"
  fi
fi
