all:
	pdflatex -file-line-error -halt-on-error proposal

clean:
	rm -f *.aux *.blg *.bbl *.dvi *.log

clobber: clean
	rm -f proposal.ps proposal.pdf proposal.ilg proposal.out proposal.toc proposal.idx proposal.ind
