#include "deviceAttributes.h"
#include <stdio.h>

void runBaselineVersion(void) {
  printf("name: chapel-cpu-as-device-gpu\n");
  printf("maxThreadsPerBlock: -1\n");
  printf("maxBlockDimX: -1\n");
  printf("maxBlockDimY: -1\n");
  printf("maxBlockDimZ: -1\n");
  printf("maxGridDimX: -1\n");
  printf("maxGridDimY: -1\n");
  printf("maxGridDimZ: -1\n");
  printf("maxSharedMemoryPerBlock: -1\n");
  printf("totalConstantMemory: -1\n");
  printf("warpSize: -1\n");
  printf("maxPitch: -1\n");
  printf("maximumTexture1dWidth: -1\n");
  printf("maximumTexture2dWidth: -1\n");
  printf("maximumTexture2dHeight: -1\n");
  printf("maximumTexture3dWidth: -1\n");
  printf("maximumTexture3dHeight: -1\n");
  printf("maximumTexture3dDepth: -1\n");
  printf("maxRegistersPerBlock: -1\n");
  printf("clockRate: -1\n");
  printf("textureAlignment: -1\n");
  printf("texturePitch_alignment: -1\n");
  printf("multiprocessorCount: -1\n");
  printf("kernelExecTimeout: -1\n");
  printf("integrated: -1\n");
  printf("canMapHostMemory: -1\n");
  printf("computeMode: -1\n");
  printf("concurrentKernels: -1\n");
  printf("eccEnabled: -1\n");
  printf("pciBusId: -1\n");
  printf("pciDeviceId: -1\n");
  printf("memoryClockRate: -1\n");
  printf("globalMemoryBusWidth: -1\n");
  printf("l2CacheSize: -1\n");
  printf("maxThreadsPerMultiprocessor: -1\n");
  printf("computeCapabilityMajor: -1\n");
  printf("computeCapabilityMinor: -1\n");
  printf("maxSharedMemoryPerMultiprocessor: -1\n");
  printf("managedMemory: -1\n");
  printf("multiGpuBoard: -1\n");
  printf("pageableMemoryAccess: -1\n");
  printf("concurrentManagedAccess: -1\n");
  printf("pageableMemoryAccessUsesHostPageTables: -1\n");
  printf("directManagedMemAccessFromHost: -1\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
  printf("warning: querying gpu attributes is currently unsupported in cpu-as-device mode.\n");
}
