var b: _bytes = "some\t\x00bytes with € (the euro char)";
writeln("Length :", b.numBytes);
writeln();
writef("<%|36s>\n", b);
writeln();
writef("<%|*s>\n", 36, b);
writeln();
writef("<%|0S>\n", b);
writeln();
writef("<%|1S>\n", b);
writeln();
writef("<%|2S>\n", b);
writeln();
writef("<%|4S>\n", b);
writeln();
writef("<%|8S>\n", b);
writeln();
writef("<%|*S>\n", 1, b);
writeln();
writef("<%|vS>\n", b);
writeln();
writef("<%ht>\n", b);
