var b = b"test";
writef("<%|4s> ", b);
writef("<%|*s> ", 4, b);
writef("<%|0S> ", b);
writef("<%|1S> ", b);
writef("<%|2S> ", b);
writef("<%|4S> ", b);
writef("<%|8S> ", b);
writef("<%|*S> ", 1, b);
writef("<%|vS> ", b);
