01-error-global.chpl:80: error: illegal lvalue in assignment
01-error-global.chpl:81: error: illegal lvalue in assignment
01-error-global.chpl:82: error: illegal lvalue in assignment
01-error-global.chpl:83: error: illegal lvalue in assignment
01-error-global.chpl:84: error: illegal lvalue in assignment
01-error-global.chpl:85: error: illegal lvalue in assignment
01-error-global.chpl:86: error: illegal lvalue in assignment
01-error-global.chpl:87: error: illegal lvalue in assignment
01-error-global.chpl:88: error: illegal lvalue in assignment
01-error-global.chpl:89: error: illegal lvalue in assignment
01-error-global.chpl:90: error: illegal lvalue in assignment
01-error-global.chpl:91: error: illegal lvalue in assignment
01-error-global.chpl:92: error: illegal lvalue in assignment
01-error-global.chpl:93: error: illegal lvalue in assignment
01-error-global.chpl:94: error: illegal lvalue in assignment
01-error-global.chpl:95: error: illegal lvalue in assignment
01-error-global.chpl:96: error: illegal lvalue in assignment
01-error-global.chpl:97: error: illegal lvalue in assignment
01-error-global.chpl:98: error: illegal lvalue in assignment
01-error-global.chpl:99: error: illegal lvalue in assignment
01-error-global.chpl:100: error: illegal lvalue in assignment
01-error-global.chpl:101: error: illegal lvalue in assignment
01-error-global.chpl:102: error: illegal lvalue in assignment
01-error-global.chpl:103: error: illegal lvalue in assignment
01-error-global.chpl:104: error: illegal lvalue in assignment
01-error-global.chpl:113: error: illegal lvalue in assignment
01-error-global.chpl:114: error: illegal lvalue in assignment
01-error-global.chpl:115: error: illegal lvalue in assignment
01-error-global.chpl:116: error: illegal lvalue in assignment
01-error-global.chpl:117: error: illegal lvalue in assignment
01-error-global.chpl:118: error: illegal lvalue in assignment
01-error-global.chpl:119: error: illegal lvalue in assignment
01-error-global.chpl:120: error: illegal lvalue in assignment
01-error-global.chpl:121: error: illegal lvalue in assignment
01-error-global.chpl:122: error: illegal lvalue in assignment
01-error-global.chpl:123: error: illegal lvalue in assignment
01-error-global.chpl:124: error: illegal lvalue in assignment
01-error-global.chpl:125: error: illegal lvalue in assignment
01-error-global.chpl:126: error: illegal lvalue in assignment
01-error-global.chpl:127: error: illegal lvalue in assignment
01-error-global.chpl:128: error: illegal lvalue in assignment
01-error-global.chpl:129: error: illegal lvalue in assignment
01-error-global.chpl:130: error: illegal lvalue in assignment
01-error-global.chpl:131: error: illegal lvalue in assignment
01-error-global.chpl:132: error: illegal lvalue in assignment
01-error-global.chpl:133: error: illegal lvalue in assignment
01-error-global.chpl:134: error: illegal lvalue in assignment
01-error-global.chpl:135: error: illegal lvalue in assignment
01-error-global.chpl:136: error: illegal lvalue in assignment
01-error-global.chpl:137: error: illegal lvalue in assignment
01-error-global.chpl:146: error: illegal lvalue in assignment
01-error-global.chpl:147: error: illegal lvalue in assignment
01-error-global.chpl:148: error: illegal lvalue in assignment
01-error-global.chpl:149: error: illegal lvalue in assignment
01-error-global.chpl:150: error: illegal lvalue in assignment
01-error-global.chpl:151: error: illegal lvalue in assignment
01-error-global.chpl:152: error: illegal lvalue in assignment
01-error-global.chpl:153: error: illegal lvalue in assignment
01-error-global.chpl:154: error: illegal lvalue in assignment
01-error-global.chpl:155: error: illegal lvalue in assignment
01-error-global.chpl:156: error: illegal lvalue in assignment
01-error-global.chpl:157: error: illegal lvalue in assignment
01-error-global.chpl:158: error: illegal lvalue in assignment
01-error-global.chpl:159: error: illegal lvalue in assignment
01-error-global.chpl:160: error: illegal lvalue in assignment
01-error-global.chpl:161: error: illegal lvalue in assignment
01-error-global.chpl:162: error: illegal lvalue in assignment
01-error-global.chpl:163: error: illegal lvalue in assignment
01-error-global.chpl:164: error: illegal lvalue in assignment
01-error-global.chpl:165: error: illegal lvalue in assignment
01-error-global.chpl:166: error: illegal lvalue in assignment
01-error-global.chpl:167: error: illegal lvalue in assignment
01-error-global.chpl:168: error: illegal lvalue in assignment
01-error-global.chpl:169: error: illegal lvalue in assignment
01-error-global.chpl:170: error: illegal lvalue in assignment
