02-error-local.chpl:43: In function 'test':
02-error-local.chpl:81: error: illegal lvalue in assignment
02-error-local.chpl:82: error: illegal lvalue in assignment
02-error-local.chpl:83: error: illegal lvalue in assignment
02-error-local.chpl:84: error: illegal lvalue in assignment
02-error-local.chpl:85: error: illegal lvalue in assignment
02-error-local.chpl:86: error: illegal lvalue in assignment
02-error-local.chpl:87: error: illegal lvalue in assignment
02-error-local.chpl:88: error: illegal lvalue in assignment
02-error-local.chpl:89: error: illegal lvalue in assignment
02-error-local.chpl:90: error: illegal lvalue in assignment
02-error-local.chpl:91: error: illegal lvalue in assignment
02-error-local.chpl:92: error: illegal lvalue in assignment
02-error-local.chpl:93: error: illegal lvalue in assignment
02-error-local.chpl:94: error: illegal lvalue in assignment
02-error-local.chpl:95: error: illegal lvalue in assignment
02-error-local.chpl:96: error: illegal lvalue in assignment
02-error-local.chpl:97: error: illegal lvalue in assignment
02-error-local.chpl:98: error: illegal lvalue in assignment
02-error-local.chpl:99: error: illegal lvalue in assignment
02-error-local.chpl:100: error: illegal lvalue in assignment
02-error-local.chpl:101: error: illegal lvalue in assignment
02-error-local.chpl:102: error: illegal lvalue in assignment
02-error-local.chpl:103: error: illegal lvalue in assignment
02-error-local.chpl:104: error: illegal lvalue in assignment
02-error-local.chpl:105: error: illegal lvalue in assignment
02-error-local.chpl:114: error: illegal lvalue in assignment
02-error-local.chpl:115: error: illegal lvalue in assignment
02-error-local.chpl:116: error: illegal lvalue in assignment
02-error-local.chpl:117: error: illegal lvalue in assignment
02-error-local.chpl:118: error: illegal lvalue in assignment
02-error-local.chpl:119: error: illegal lvalue in assignment
02-error-local.chpl:120: error: illegal lvalue in assignment
02-error-local.chpl:121: error: illegal lvalue in assignment
02-error-local.chpl:122: error: illegal lvalue in assignment
02-error-local.chpl:123: error: illegal lvalue in assignment
02-error-local.chpl:124: error: illegal lvalue in assignment
02-error-local.chpl:125: error: illegal lvalue in assignment
02-error-local.chpl:126: error: illegal lvalue in assignment
02-error-local.chpl:127: error: illegal lvalue in assignment
02-error-local.chpl:128: error: illegal lvalue in assignment
02-error-local.chpl:129: error: illegal lvalue in assignment
02-error-local.chpl:130: error: illegal lvalue in assignment
02-error-local.chpl:131: error: illegal lvalue in assignment
02-error-local.chpl:132: error: illegal lvalue in assignment
02-error-local.chpl:133: error: illegal lvalue in assignment
02-error-local.chpl:134: error: illegal lvalue in assignment
02-error-local.chpl:135: error: illegal lvalue in assignment
02-error-local.chpl:136: error: illegal lvalue in assignment
02-error-local.chpl:137: error: illegal lvalue in assignment
02-error-local.chpl:138: error: illegal lvalue in assignment
02-error-local.chpl:147: error: illegal lvalue in assignment
02-error-local.chpl:148: error: illegal lvalue in assignment
02-error-local.chpl:149: error: illegal lvalue in assignment
02-error-local.chpl:150: error: illegal lvalue in assignment
02-error-local.chpl:151: error: illegal lvalue in assignment
02-error-local.chpl:152: error: illegal lvalue in assignment
02-error-local.chpl:153: error: illegal lvalue in assignment
02-error-local.chpl:154: error: illegal lvalue in assignment
02-error-local.chpl:155: error: illegal lvalue in assignment
02-error-local.chpl:156: error: illegal lvalue in assignment
02-error-local.chpl:157: error: illegal lvalue in assignment
02-error-local.chpl:158: error: illegal lvalue in assignment
02-error-local.chpl:159: error: illegal lvalue in assignment
02-error-local.chpl:160: error: illegal lvalue in assignment
02-error-local.chpl:161: error: illegal lvalue in assignment
02-error-local.chpl:162: error: illegal lvalue in assignment
02-error-local.chpl:163: error: illegal lvalue in assignment
02-error-local.chpl:164: error: illegal lvalue in assignment
02-error-local.chpl:165: error: illegal lvalue in assignment
02-error-local.chpl:166: error: illegal lvalue in assignment
02-error-local.chpl:167: error: illegal lvalue in assignment
02-error-local.chpl:168: error: illegal lvalue in assignment
02-error-local.chpl:169: error: illegal lvalue in assignment
02-error-local.chpl:170: error: illegal lvalue in assignment
02-error-local.chpl:171: error: illegal lvalue in assignment
