#!/bin/bash
$CHPL_HOME/tools/chplcheck/chplcheck --enable-rule ConsecutiveDecls \
  --enable-rule BoolLitInCondStatement \
  --enable-rule UseExplicitModules \
  --enable-rule UnusedFormal \
  --enable-rule CamelOrPascalCaseVariables \
  $1.chpl >> $2
if sed "s#$(pwd)/##" $2 >$2.tmp; then
    mv $2.tmp $2
fi
