#!/usr/bin/env sh

#Script for removing pre-release tag and updating version number before creating release branch. Arguments are the old and new version numbers as follows:
#1 - Old Major
#2 - New Major
#3 - Old Minor
#4 - New Minor
#5 - Old Update
#6 - New Update

sed -i '' 35s/false/true/ ../../compiler/main/version_num.h
sed -i '' 83s/^/'# '/ ../../doc/rst/conf.py
sed -i '' 84s/'# '// ../../doc/rst/conf.py
sed -i '' 84s/"$1\.$3\.$5"/"$2\.$4\.$6"/ ../../doc/rst/conf.py
sed -i '' "9i\\
* \`Chapel $1\.$3 \<https://chapel-lang.org/docs/$1\.$3/index.html\>\`_
" ../../doc/rst/language/archivedSpecs.rst
sed -i '' 19s/"$1\.$3"/"$2\.$4"/ ../../doc/rst/usingchapel/QUICKSTART.rst
sed -i '' 31s/"$1\.$3\.$5"/"$2\.$4\.$6"/ ../../doc/rst/usingchapel/QUICKSTART.rst
sed -i '' 38s/"$1\.$3\.$5"/"$2\.$4\.$6"/ ../../doc/rst/usingchapel/QUICKSTART.rst
sed -i '' 40s/"$1\.$3\.$5"/"$2\.$4\.$6"/ ../../doc/rst/usingchapel/chplenv.rst
sed -i '' 2s/' pre-release'// ../../man/confchpl.rst
sed -i '' 2s/' pre-release'// ../../man/confchpldoc.rst
sed -i '' 8s/^/'# '/ ../../test/compflags/bradc/printstuff/versionhelp.sh
sed -i '' 9s/^/'# '/ ../../test/compflags/bradc/printstuff/versionhelp.sh
sed -i '' 11s/'# '// ../../test/compflags/bradc/printstuff/versionhelp.sh