#!/bin/tcsh

set grep = grep
if `uname -s` == "SunOS" then
    set grep = /usr/xpg4/bin/grep
endif

cd $CHPL_HOME/runtime

$grep -e "$argv" include/*.h include/*/*.h src/*.c src/*.chpl comm-none/*.c comm-gasnet/*.c threads-*/*.c 

cd -
