#!/usr/bin/perl

$home = $ENV{'CHPL_HOME'};

die "CHPL_HOME must be set" unless $home;

$printusage = 0;

$username = "";
if (@ARGV) {
    $flag = shift @ARGV;
    if ($flag eq "--help" || $flag eq "-h") {
        $printusage = 1;
    } else {
        $username = $flag;
    }
    if (@ARGV) {
        $printusage = 1;
    }
}

if ($printusage) {
    print "list_futures [<username>]\n";
    exit 0;
}

if ($username ne "") {
    print "***running for user: $username\n";
}


@fnames = `find $home/test -name *.future`;

foreach $fname (@fnames) {
  chomp $fname;
  $worker = `head -n 1 $fname`;
  chomp $worker;
  $fname =~ s/.*test\/(.*)\.future$/test\/$1/;
  if (index($worker, $username) != -1) {
      push @output, "$worker [$fname]\n";
  }
}

@sorted = sort { lc($a) cmp lc($b) } @output;

foreach $line (@sorted) {
  print $line;
}
