#!/usr/bin/perl

$home = $ENV{'CHPL_HOME'};

die "CHPL_HOME must be set" unless $home;

$printusage = 0;

$username = "";
while (@ARGV) {
    $flag = shift @ARGV;
    if ($flag eq "--help" || $flag eq "-h") {
        $printusage = 1;
    } elsif ($flag eq "--show-first-revision-numbers") {
        $nrevs = 1;
    } else {
        if ($username ne "") {
            $printusage = 1;
        }
        $username = $flag;
    }
}

if ($printusage) {
    print "list_futures [--show-first-revision-numbers] [<username>]\n";
    exit 0;
}

if ($username ne "") {
    print "***running for user: $username\n";
}


@fnames = `find $home/test -name .svn -prune ! -name .svn -or ! -name .svn ! -name . -name *.future`;

foreach $fname (@fnames) {
    chomp $fname;
    $worker = `head -n 1 $fname`;
    chomp $worker;
    if (index($worker, $username) != -1) {
        if ($nrevs) {
            @log = `svn log $fname`;
            foreach $line (@log) {
                if ($line =~ /^r(\d+)\ \|/) {
                    $num = "$1 ";
                }
            }
        }
        $fname =~ s/.*test\/(.*)\.future$/test\/$1/;
        push @output, "$num$worker [$fname]\n";
    }
}

if ($nrevs) {
    @sorted = sort { $a <=> $b } @output;
} else {
    @sorted = sort { lc($a) cmp lc($b) } @output;
}

foreach $line (@sorted) {
    print $line;
}
