#!/usr/bin/env bash

# mason requires CHPL_COMM=none CHPL_REGEXP=re2

if [ "$CHPL_COMM" != none -o "$CHPL_REGEXP" != re2 -o "$CHPL_HOST_PLATFORM" != linux64 -o "$CHPL_HOST_COMPILER" != gnu ]; then
    echo True
    exit 0
fi

# This test should only run on CentOS or similar
# Examine /etc/os-release
(
    # this subshell is like an exception handler
    set -e
    if [ -f /etc/os-release ]; then
        source /etc/os-release
        case "$ID $ID_LIKE" in
        ( *centos* | *rhel* | *fedora* ) echo False;;
        ( * ) echo True;;
        esac
    else
        echo True
    fi
)

case "$?" in
( 0 )   exit 0;;
( * )   echo True; exit 2;;
esac
