#!/usr/bin/env bash

if [[ "$CHPL_COMM" != "none" ]]; then
  echo "True"
  exit 0
fi

# this can remove too much of the debug info
if [[ "$COMPOPTS" == *"--fast"* ]]; then
  echo "True"
  exit 0
fi

# baseline testing has extra call_temps left behind that mess up the good file
if [[ "$COMPOPTS" == *"--baseline"* ]]; then
  echo "True"
  exit 0
fi

# valgrind messes up output
if [[ "$CHPL_TEST_VGRND_EXE" == "on" ]]; then
  echo "True"
  exit 0
fi

if command -v gdb >/dev/null ; then
  echo "False"
else
  echo "True"
fi
