.TH ifa 1 "Jan 2006" IFA "Manual"
.SH NAME
.PP
IFA \- Iterative Flow Analysis
.SH SYNOPSIS
.PP
.B ifa
[\fIoptions\fP]
.SH DESCRIPTION
.PP
IFA is the front end for the Iterative Flow Analysis library.
.SH OPTIONS
.PP
.IP "-t"
Write the program in HTML.
.IP "-G"
Generate program graphs.
.IP "--graph-format"
Select either GraphViz or VCG graphs.
.IP "-v"
Increase verbosity.
.IP "-d"
Increase debugging.
.IP "-h"
Display help.
.SH FEATURES
.PP
The features are covered in the documentation.  See the README file.
.SH FILES
.PP
None.	
.SH NO WARRANTIES
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.PP
IFA Home Page: http://ifa.sourceforge.net/
.PP
The MIT License.
.SH AUTHOR
.PP
John Plevyak.  Use <jplevyak at users.sourceforge.net> to contact.

