.TH ifa 1 "Jan 2006" IFA "Manual"
.SH NAME
.PP
IFA \- Iterative Flow Analysis
.SH SYNOPSIS
.PP
.B ifa
[\fIoptions\fP]
.SH DESCRIPTION
.PP
IFA is the front end for the Iterative Flow Analysis library.
.SH OPTIONS
.PP
.IP "-v"
Increase verbosity.
.IP "-d"
Increase debugging.
.IP "-h"
Display help.
.SH FEATURES
.PP
The features are covered in the documentation.  See the README file.
.SH FILES
.PP
None.	
.SH NO WARRANTIES
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
COPYRIGHT for more details.
.PP
IFA Home Page: http://ifa.sourceforge.net/
.PP
The BSD General Public License.
.SH AUTHOR
.PP
John Plevyak.  Use <jplevyak at users.sourceforge.net> to contact.

