#!/bin/bash
#
# This is a git commit hook which automatically add a DCO signed-off
# message if one is missing.  This message appends after the generation
# of git default message.
#
# To utilize this script, place this file under .git/hooks/commit-msg
#

MESSAGE_FILE="$1"
GIT_AUTHOR=$(git var GIT_AUTHOR_IDENT)
SIGNOFF_BY=$(echo $GIT_AUTHOR | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')

# Verify if a DCO signoff message exists.
# Append a DCO signoff message if one doesn't exist and print-out the warning message.
if ! $(grep -qs "^$SIGNOFF_BY" "$MESSAGE_FILE") ; then
  echo -e "\n$SIGNOFF_BY" >> "$MESSAGE_FILE"
  echo -e "Appended the following signoff to the end of the commit message:\n  $SIGNOFF_BY\n"
fi
