COMM_LAUNCHER_SRCS = \
        chpl_cfg_comm_locales.c \

COMM_SRCS = \
	$(COMM_LAUNCHER_SRCS) \
	chpl_cfg_comm.c \

SVN_SRCS = $(COMM_SRCS)
SRCS = $(SVN_SRCS)

COMM_OBJS = \
	$(COMM_SRCS:%.c=$(COMM_OBJDIR)/%.o)

COMM_LAUNCHER_OBJS = \
	$(COMM_LAUNCHER_SRCS:%.c=$(COMM_LAUNCHER_OBJDIR)/%.o)

