writeln("This is a string literal containing a backslash (\\)");
writeln("This is a string literal ending in a backslash \\");
writeln("This is a string literal ending in two backslashes \\\\");
writeln("This is a string literal\tcontaining a tab\nand line-end.");
writeln();
writeln('This is a single-quoted string containing a backslash (\\)');
writeln('This is a single-quoted string ending in a backslash \\');
writeln('This is a single-quoted string ending in two backslashes \\\\');
writeln('This is a single-quoted string\tcontaining a tab\nand a newline.');
writeln();
writeln("\\A starting backslash");
writeln("\\\\Two starting backslashes");
writeln('\\A starting backslash');
writeln('\\\\Two starting backslashes');
writeln();
writeln(" A single quote within a double-quoted string: '.");
writeln(" A single quote ending a double-quoted string: '");
writeln("'A single quote starting a double-quoted string.");
writeln(" A double quote within a double-quoted string: \".");
writeln(" A double quote ending a double-quoted string: \"");
writeln("\"A double quote starting a double-quoted string.");
writeln();
writeln(' A single quote within a single-quoted string: \'.');
writeln(' A single quote ending a single-quoted string: \'');
writeln('\'A single quote starting a single-quoted string.');
writeln(' A double quote within a single-quoted string: ".');
writeln(' A double quote ending a single-quoted string: "');
writeln('"A double quote starting a single-quoted string.');
writeln();
writeln("DONE.");
