#!/usr/bin/env sh

#Script for removing pre-release tag and updating version number before creating release branch. Arguments are the old and new version numbers as follows:
#(E.G. Release 1.24.0 to Release 1.25.0)
#1 - Old Major - 1
#2 - New Major - 1
#3 - Old Minor - 24
#4 - New Minor - 25
#5 - Old Update - 0
#6 - New Update - 0
#7 - Older Major(For archivedSpecs only) - 1
#8 - Older Minor(For archivedSpecs only) - 23

usage="changePrerelease [-h] [-options]
-h: help
options:
Arguments for E.G. Release 1.24.0 to Release 1.25.0
1 - Old Major - 1
2 - New Major - 1
3 - Old Minor - 24
4 - New Minor - 25
5 - Old Update - 0
6 - New Update - 0
7 - Older Major(For archivedSpecs only) - 1
8 - Older Minor(For archivedSpecs only) - 23"

while getopts 'h' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage"
       exit 1
       ;;
  esac
done

if [ $# -ne 8 ]
  then
    echo "Incorrect number of arguments"
    echo "$usage"
    exit
fi

# manipulate the sed command because -i doesn't behave the same on macOS and Linux
# we create sed -i '' for macOS and sed -i for Linux
# However, this does not seem to work on macOS in any of the following forms:
# sed -i''
# sed -i ''
# sed -i'' -e
sed_command="sed -i"
if [[ $OSTYPE == 'darwin'* ]]; then
  sed_command="sed -i'' -e"
fi

echo "Changing officialRelease to true in CMakeLists.txt"
$sed_command '/set(CHPL_OFFICIAL_RELEASE/ s/false/true/' $CHPL_HOME/CMakeLists.txt

echo "Changing release number in conf.py"
$sed_command "/^release =/s/^/# /" $CHPL_HOME/doc/rst/conf.py
$sed_command "/release = '$1\.$3\.$5'/s/# //" $CHPL_HOME/doc/rst/conf.py
$sed_command "/release = '$1\.$3\.$5'/s/"$1\.$3\.$5"/"$2\.$4\.$6"/" $CHPL_HOME/doc/rst/conf.py

echo "Adding last release to archivedSpecs.rst"
$sed_command "/* \`Chapel $7\.$8/i\\
* \`Chapel $1\.$3 \<https://chapel-lang.org/docs/$1\.$3/\>\`_
" $CHPL_HOME/doc/rst/language/archivedSpecs.rst

echo "Changing version numbers in QUICKSTART.rst"
$sed_command "/1)/s/"$1\.$3"/"$2\.$4"/" $CHPL_HOME/doc/rst/usingchapel/QUICKSTART.rst
$sed_command "/tar xzf/s/"$1\.$3\.$5"/"$2\.$4\.$6"/" $CHPL_HOME/doc/rst/usingchapel/QUICKSTART.rst
$sed_command "/cd chapel/s/"$1\.$3\.$5"/"$2\.$4\.$6"/" $CHPL_HOME/doc/rst/usingchapel/QUICKSTART.rst

echo "Changing version number in chplenv.rst"
$sed_command "/export CHPL_HOME/s/"$1\.$3\.$5"/"$2\.$4\.$6"/" $CHPL_HOME/doc/rst/usingchapel/chplenv.rst

echo "Changing version number in confchpl.rst and confchpldoc.rst"
$sed_command /Version/s/' pre-release'// $CHPL_HOME/man/confchpl.rst
$sed_command /Version/s/' pre-release'// $CHPL_HOME/man/confchpldoc.rst

echo "Changing output in versionhelp.sh"
$sed_command "/diff $CWD/s/^/# /" $CHPL_HOME/test/compflags/bradc/printstuff/versionhelp.sh
$sed_command "/{ echo/s/^/# /" $CHPL_HOME/test/compflags/bradc/printstuff/versionhelp.sh
$sed_command "/# echo ""/s/# //" $CHPL_HOME/test/compflags/bradc/printstuff/versionhelp.sh
