#!/usr/bin/env perl

my $testname = $ARGV[0];
my $outputdir = $ARGV[1];
my $testdir = $ARGV[2];
my $searchdir = ".";

my $duplicate_src = "$searchdir/dupsrc.tmp";
system("find $searchdir -name \\$testname.chpl > $duplicate_src");
open DUPLICATES, "$duplicate_src" or die "can't open $duplicate_src $!";
my @duplicates = <DUPLICATES>;
system("rm $duplicate_src");
exit &getNumDuplicates;

sub getNumDuplicates {
    if ($#duplicates > 0) {
        print "[Error: found $#duplicates src files:";
        foreach my $duplicate(@duplicates) {
            chomp($duplicate);
            print " $duplicate";
        }
        print "]\n";
    }
    return $#duplicates;
}

