#!/usr/bin/env python
#
# This script is a system-wide prediff for use with the OpenMPI mpirun
# launcher.  Depending on how OpenMPI is configured, when mpirun sees
# a program it launched exit with a non-zero status, it may print either
# messages like this:
#     -------------------------------------------------------
#     Primary job  terminated normally, but 1 process returned
#     a non-zero exit code.. Per user-direction, the job has been aborted.
#     -------------------------------------------------------
#
# or messages like this:
#     -------------------------------------------------------
#     While the primary job  terminated normally, 1 process returned
#     a non-zero exit code.. Further examination may be required.
#     -------------------------------------------------------
#
# This script removes such messages.
#
import sys, os, re

# These match the message blocks we want to remove.
msgs = (
"""^-------------------------------------------------------
Primary job +terminated normally, but [0-9]+ process[^ ]* returned
a non-zero exit code[.]+ Per user-direction, the job has been aborted[.]
-------------------------------------------------------
""",
"""^-------------------------------------------------------
While the primary job +terminated normally, [0-9]+ process[^ ]* returned
a non-zero exit code[.]+ Further examination may be required[.]
-------------------------------------------------------
"""
)

outfname = sys.argv[2]
with open(outfname, "r") as f:
    outText = f.read()
for m in msgs:
    outText = re.sub(m, "", outText, flags = re.MULTILINE)
with open(outfname, "w") as f:
    f.write(outText)
