#!/usr/bin/env python3

import sys
import os
import re

testname=sys.argv[1]
outfile=sys.argv[2]

lines = [l.strip() for l in open(outfile, "r").readlines()]

outlines = []
idx = 0
r = re.compile(r"^.*\.chpl:(\d+): .*(?:KEEP ME)?: (.*)$")
while idx < len(lines):
    l = lines[idx]
    keep = False
    useCompilerMsg = False
    if "In function 'foo':" in l:
        idx += 1
        l = lines[idx]
        keep = True
        useCompilerMsg = "KEEP ME" in l
    
    if keep:
        m = re.match(r, l)
        if m:
            msg = m[2] if useCompilerMsg else "compiler error"
            outlines.append((int(m[1]), msg))
        else:
            outlines.append(l)

    idx += 1

outlines = sorted(outlines, key=lambda x: x[0])

open(outfile, "w").writelines([f"{l[0]} - {l[1]}\n" for l in outlines])

