#!/bin/bash

testname=$1
outputfile=$2
compiler=$3

doSort=true
doRLN=false

# test-specific
case $testname in
  (t8)  doRLN=true ;;
  (t5a) doRLN=true; doSort=false ;;
  (s7)  doSort=false ;;
  (tmath) doSort=false ;;
  (hplx)
     # special handling
     mv $outputfile $outputfile.orig

     # There is no consistent failing output.
     # These filters are an attempt to distinguish failure reliably
     # (the absense of the 'start...finish' line) plus guard against
     # other failures like syntax errors.
     # The error "ReplicatedDist.chpl:272: error: attempt to dereference nil"
     # or similar is sometimes reported in a failed run, sometimes not.

     egrep -i '^start...finish$|error|warning' $outputfile.orig \
       | grep -v 'error: attempt to dereference nil' \
       > $outputfile

     # preserve $outputfile.orig
     ;; #hplx
esac

# remove line numbers from warnings
if $doRLN; then
  sed 's@\.chpl:[1-9][0-9]*:@.chpl:@' $outputfile > $outputfile.tmp && \
  mv $outputfile.tmp $outputfile
fi

# sort the output
if $doSort; then
  sort $outputfile > $outputfile.tmp  && \
  mv $outputfile.tmp $outputfile
fi
