#!/bin/bash
TESTNAME=$1
OUTFILE=$2

# If the test failed to compile, fail
HAS_COMPILE_ERROR=`grep "error:" $OUTFILE`
if [ -n "$HAS_COMPILE_ERROR" ]; then
  exit 0
fi

LL_FILE=$TESTNAME.ll
if [ ! -f "$LL_FILE" ]; then
  echo "Expected LLVM IR file $LL_FILE not found!" >> $OUTFILE
  exit 0
fi

TMPFILE="$LL_FILE.prediff.tmp"

LLVM_CONFIG=`${CHPL_HOME}/util/chplenv/chpl_llvm.py --llvm-config`
BINDIR=`${LLVM_CONFIG} --bindir`
FILECHECK="${BINDIR}/FileCheck"
if command -v $FILECHECK >/dev/null; then
  FILECHECK=`command -v $FILECHECK`
else
  PREFIX=`${LLVM_CONFIG} --prefix`
  FILECHECK="${PREFIX}/libexec/llvm/FileCheck"
fi

OPT="${BINDIR}/opt"
# run some passes to simplify the IR for easier checking
$OPT -S -passes='mem2reg,simplifycfg' $LL_FILE -o $TMPFILE


$FILECHECK --enable-var-scope --input-file $TMPFILE $TESTNAME.chpl 2>> $OUTFILE

# Make sure to propagate memory leaks
awk '/=* Memory Leaks =*/ {intable=1} {if (intable) {print($0);}}' <$TMPFILE >>$OUTFILE

rm $TMPFILE
