set(CMAKE_CHPL_COMPILE_OBJECT "cp <SOURCE> <OBJECT>")
set(CMAKE_CHPL_LINK_EXECUTABLE "<CMAKE_CHPL_COMPILER> -o <TARGET> <OBJECTS> <FLAGS> <LINK_FLAGS>")
# <COMPILE_FLAGS> doesn't work on link step

set(CMAKE_CHPL_SOURCE_FILE_EXTENSIONS chpl)

set(CMAKE_CHPL_OUTPUT_EXTENSION "")


set(CMAKE_CHPL_FLAGS_RELEASE "--fast")
set(CMAKE_CHPL_FLAGS_DEBUG "-g")
