s/CHPL_STM_LOAD/CHPL_DUMMY_STM_LOAD/g
s/CHPL_DUMMY_STM_LOAD_REF(\(tx, T[0-9]*, local__ret[0-9]*, uint64_t\)/CHPL_STM_LOAD_REF(\1/g
s/CHPL_STM_ARRAY_LOAD/CHPL_DUMMY_STM_ARRAY_LOAD/g
s/CHPL_STM_TX_ALLOC_PERMIT_ZERO/CHPL_DUMMY_STM_TX_ALLOC_PERMIT_ZERO/g
s/chpl_stm_tx_free(tx, /chpl_free(/g
s/CHPL_STM_COMM_WIDE_GET/CHPL_DUMMY_STM_COMM_WIDE_GET/g
s/CHPL_DUMMY_STM_COMM_WIDE_GET(\(tx, T[0-9]*, _ret[0-9]*, uint64_t\)/CHPL_STM_COMM_WIDE_GET(\1/g
s/CHPL_STM_COMM_WIDE_ARRAY_GET/CHPL_DUMMY_STM_COMM_WIDE_ARRAY_GET/g
