SYMTAB_SRCS = \
        codegenOne.cpp \
	collectSymbols.cpp \
        copyPropagation.cpp \
        normalizeFunctions.cpp \
        postAnalysisCleanup.cpp \
	printSymtab.cpp \
	removeDeadSymbols.cpp \
        resolveTypes.cpp \
	symscope.cpp \
        symtab.cpp \
	symtabTraversal.cpp

CVS_SRCS = $(SYMTAB_SRCS)
SRCS = $(CVS_SRCS)

SYMTAB_OBJS = \
	$(SYMTAB_SRCS:%.cpp=$(SYMTAB_OBJDIR)/%.$(OBJ_SUFFIX))
