SYMTAB_SRCS = \
	collectSymbols.cpp \
        copyPropagation.cpp \
        resolveTypes.cpp \
	symscope.cpp \
        symtab.cpp \
	symtabTraversal.cpp

CVS_SRCS = $(SYMTAB_SRCS)
SRCS = $(CVS_SRCS)

SYMTAB_OBJS = \
	$(SYMTAB_SRCS:%.cpp=$(SYMTAB_OBJDIR)/%.$(OBJ_SUFFIX))
