RUNTIME_ROOT = ../..
RUNTIME_SUBDIR = src/tasks

#
# standard header
#
include $(RUNTIME_ROOT)/make/Makefile.runtime.head

TARGETS =

SUBDIRS = $(CHPL_MAKE_TASKS)

include $(RUNTIME_ROOT)/make/Makefile.runtime.emptydirrules

FORCE:

#
# standard footer
#
include $(RUNTIME_ROOT)/make/Makefile.runtime.foot
