#!/usr/bin/env perl

use File::Basename;

$utildirname = dirname($0);
$commscript = "$utildirname/comm";

$preset_mpi = $ENV{'CHPL_MPI_VERSION'};

if ($preset_mpi eq "") {
    $comm = `$commscript $flag`;
    chomp($comm);
    if ($comm eq "armci") {
        $mpi = "mpich1";
    } else {
        $mpi = "openmpi";
    }
} else {
    $mpi = $preset_mpi;
}

print "$mpi\n";
exit(0);
