#!/usr/bin/env perl

use FindBin;
use lib $FindBin::Bin;
use Run qw(ret run);
use strict;


my $home = $ENV{'CHPL_HOME'};
if ( ! -d $home ) {
  $home = $FindBin::Bin . "/../../";
}

my $preset_hwloc = $ENV{'CHPL_HWLOC'};
my $hwloc;

if ($preset_hwloc eq "") {
  my $tasks = run("tasks");
  if ($tasks eq "qthreads") {
    $hwloc = 'hwloc';
  } else {
    $hwloc = 'none';
  }
} else {
  $hwloc = $preset_hwloc;
}

ret($hwloc);
print "$hwloc\n" unless caller;
