#!/usr/bin/env perl

use FindBin;
use lib $FindBin::Bin;
use Run qw(ret run);
use strict;

my $preset_tasks   = $ENV{'CHPL_TASKS'};
my $preset_threads = $ENV{'CHPL_THREADS'};
my $tasks;

if ($preset_tasks eq "") {
    if ($preset_threads =~ /^(minimal|pthreads)$/) {
        $tasks = "fifo";
    } elsif ($preset_threads eq "soft-threads") {
        $tasks = "muxed";
    } elsif ($preset_threads eq "") {
        $tasks = "fifo";
    } else {
		die "Unexpected CHPL_THREADS value \"$preset_threads\".\n";
    }
} else {
    $tasks = $preset_tasks;
}

if ($preset_threads ne "") {
    run("check-tasks-threads-compatibility", $tasks, $preset_threads);
}

ret($tasks);
print "$tasks\n" unless caller;
