//
// This C++ program uses runtime headers in order to generate a Chapel
// module which prepares the data entries of a 'chpl_rt_prginfo'
// struct on a given locale. The entries can be found in the runtime
// header 'chpl-prginfo-data-macro.h'.
//
// The module contents currently do not vary based on the Chapel
// configuration, so the output directory does not need a cfg-based
// prefix.
//

#include "chpl-prginfo.h"
#include <algorithm>
#include <array>
#include <fstream>
#include <iostream>
#include <string>
#include <utility>
#include <vector>

#define STR_INNER(x__) #x__
#define STR(x__) STR_INNER(x__)
#define INDENT(n__) std::string(n__, ' ')

#define CALLBACK_TYPE(ret_type__, ...) ret_type__ (*)(__VA_ARGS__)

using build_constant_list = std::vector<std::string>;

const char* module_name = "ChapelSetProgramInfoDataEntries";
const char* setter_proc_name = "chpl_setProgramInfoDataEntriesHere";
const char* lookup_proc_name = "chpl_lookupProgramBuildConstant";
const char* program_formal_name = "prg";
const char* program_type = "chpl_programInfo";

static std::ofstream& out_typedef_name(std::ofstream& ofs,
                                       const char* symbol) {
  ofs << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_PREFIX) << symbol
      << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_SUFFIX);
  return ofs;
}

static std::ofstream& out_fnptr_type(std::ofstream& ofs,
                                     const char* name,
                                     const char* ret_type,
                                     const char* formals) {
  ofs << ret_type << " (*" << name << ")(" << formals << ")";
  return ofs;
}

static void expand_constant(std::ofstream& ofs, int indent,
                            const char* name,
                            const char* type) {
  ofs << INDENT(indent);
  ofs << "// C symbol: '" << type << " " << name << "'\n";
  ofs << INDENT(indent);
  ofs << "extern type ";
  out_typedef_name(ofs, name) << ";\n";
  ofs << INDENT(indent);
  ofs << "extern const " << name << ": ";
  out_typedef_name(ofs, name) << ";\n";
  ofs << INDENT(indent);
  ofs << program_formal_name << ".setConstant(\'" << name << "\', " << name;
  ofs << ");\n";
}

static void expand_callback(std::ofstream& ofs, int indent,
                            const char* name,
                            const char* ret_type,
                            const char* formals) {
  ofs << INDENT(indent);
  ofs << "// C symbol: '";
  out_fnptr_type(ofs, name, ret_type, formals) << "'\n";
  ofs << INDENT(indent);
  ofs << program_formal_name << ".setCallback(\'" << name << "\');\n";
}

static void print_setter_proc(std::ofstream& ofs, int indent) {
  ofs << INDENT(indent);
  ofs << "proc " << setter_proc_name << "(ref " << program_formal_name << ": ";
  ofs << program_type << ") {\n";

  #define E_CONSTANT(name__, type__) do { \
    expand_constant(ofs, indent+2, #name__, #type__); \
  } while (0);

  #define E_CALLBACK(name__, ret_type__, ...) do { \
    expand_callback(ofs, indent+2, #name__, #ret_type__, #__VA_ARGS__); \
  } while (0);

  #include "chpl-prginfo-data-macro-adapter.h"

  ofs << INDENT(indent);
  ofs << "}\n";
}

static void print_global_decls(std::ofstream& ofs, int indent) {
  ofs << INDENT(indent);
  ofs << "use ChapelProgramRegistration;\n";
  ofs << INDENT(indent);
  ofs << "use CTypes;\n";
  ofs << INDENT(indent);
  ofs << "use ChapelBase;\n";
  ofs << "\n";
  ofs << INDENT(indent);
  ofs << "extern proc strcmp(x: c_ptrConst(c_char), y: x.type): c_int;\n";
}

static void print_lookup_proc_body(std::ofstream& ofs,
                                   const char* constant_formal_name,
                                   const build_constant_list& bcl,
                                   int indent) {
  for (auto& constant : bcl) {
    ofs << INDENT(indent);
    ofs << "if 0 == strcmp(" << "\"" << constant << "\"";
    ofs << ", " << constant_formal_name << ") {\n";
    ofs << INDENT(indent+2);
    ofs << "extern const " << constant << ": c_ptrConst(c_char);\n";
    ofs << INDENT(indent+2);
    ofs << "return " << constant << ";\n";
    ofs << INDENT(indent);
    ofs << "}\n";
  }

  ofs << INDENT(indent);
  ofs << "return nil;\n";
}

static
void print_build_constant_lookup_proc(std::ofstream& ofs,
                                      const build_constant_list& bcl,
                                      int indent) {
  const char* constant_formal_name = "name";
  const char* c_string_type = "c_ptrConst(c_char)";

  ofs << INDENT(indent);
  ofs << "export proc " << lookup_proc_name << "(";
  ofs << constant_formal_name << ": " << c_string_type;
  ofs << "): " << c_string_type << " {\n";

  print_lookup_proc_body(ofs, constant_formal_name, bcl, indent+2);

  ofs << INDENT(indent);
  ofs << "}\n";
}

static
void print_module_code(std::ofstream& ofs, const build_constant_list& bcl) {
  ofs << "// This module was automatically generated by a script.\n";
  ofs << "module " << module_name << " {\n";
  print_global_decls(ofs, 2);
  ofs << "\n";
  print_build_constant_lookup_proc(ofs, bcl, 2);
  ofs << "\n";
  print_setter_proc(ofs, 2);
  ofs << "}";
}

int main(int argc, const char** argv) {
  if (argc != 2) {
    std::cerr << "Expected 1 argument: a writeable file path" << std::endl;
    return 1;
  }

  auto path = argv[1];
  std::ofstream ofs(path);

  if (!ofs.is_open()) {
    std::cerr << "Failed to open '" << path << "'" << std::endl;
    return 1;
  }

  build_constant_list bcl;

  std::string line;
  while (std::getline(std::cin, line)) {
    auto pos = line.find('=');
    assert(pos != std::string::npos);
    auto constant = line.substr(0, pos);
    bcl.push_back(std::move(constant));
  }

  std::sort(bcl.begin(), bcl.end());

  if (bcl.empty()) {
    std::cerr << "Did not read any build constants from stdin!" << std::endl;
    return 1;
  }

  print_module_code(ofs, bcl);

  ofs.close();

  return 0;
}
