#!/usr/bin/env python3

import optparse
import os
import re
import sys

# Gain access to the scripts in '$CHPL_HOME/util/chplenv'.
script_dir = os.path.dirname(os.path.realpath(__file__))
chpl_home_dir = os.path.dirname(os.path.dirname(script_dir))
chplenv_dir = os.path.join(chpl_home_dir, "util", "chplenv")
sys.path.insert(0, os.path.abspath(chplenv_dir))

import printchplenv


def invoke_printchplenv_wrapper():
    # Populate ENV_VALS as 'main' does in 'printchplenv.py'...
    printchplenv.compute_all_values()
    # This is the exact set of arguments needed to match the following:
    # printchplenv --runtime --no-tidy --anonymize --simple
    got = printchplenv.printchplenv(
        contents=set(["runtime"]),
        print_filters=set(["anonymize"]),
        print_format="simple",
        only=None,
        raw=False,
    )
    ret = {}
    for line in got.split("\n"):
        parts = line.split("=", maxsplit=1)
        if not line or not parts:
            continue
        assert len(parts) == 2
        k = parts[0].strip()
        v = parts[1].strip()
        ret[k] = v
    return ret


def generate_env_defines(env):
    ret = "// Macros to use in preprocessor '#if' directives...\n"
    for k, v in env.items():
        # Replace any character that is not a letter, number, or underscore.
        macro_name = re.sub(r"[^a-zA-Z0-9_]", "_", v).upper()
        ret += "#define " + "_".join((k.upper(), macro_name)) + "\n"
    ret += "\n"
    ret += "// Macro constants to use with 'strcmp'...\n"
    for k, v in env.items():
        macro_name = k.upper() + "_RT"
        ret += " ".join(("#define", macro_name, f'"{v}"')) + "\n"
    return ret


def quote(s):
    return '"' + str(s) + '"'


def generate_env_lookup_table(env):
    ret = str()
    ret += "// Sorted lookup table expression for use at runtime.\n"
    ret += "// This is a null-terminated array of 'const char*[2]'.\n"
    size = len(env)
    ret += f"#define CHPL_RT_ENV_LOOKUP_TABLE_SIZE {size}\n"
    ret += "#define CHPL_RT_ENV_LOOKUP_TABLE_INIT_EXPR { \\\n"
    for k in sorted(env.keys()):
        entry_k = k.upper()
        entry_v = env[k]
        ret += "  {" + ", ".join((quote(entry_k), quote(entry_v)))
        ret += "}, \\\n"
    ret += "  { NULL, NULL } \\\n"
    ret += "}\n"
    return ret


def generate_env_header_str(env, template_str):
    ret = template_str
    ret += "/* THIS FILE IS AUTOMATICALLY GENERATED */\n"
    ret += "#ifndef _CHPL_ENV_GEN_H_\n"
    ret += "#define _CHPL_ENV_GEN_H_\n"
    ret += "\n"
    ret += generate_env_defines(env)
    ret += "\n"
    ret += generate_env_lookup_table(env)
    ret += "\n"
    ret += "#endif /* _CHPL_ENV_GEN_H_ */"
    return ret


# Argument (1) is the path to the template file.
# Argument (2) is the output path for the env header.
def main():
    expected = 2
    if len(sys.argv) - 1 != expected:
        print(f"Expected exactly {expected} arguments!", f=stderr)
        return
    path_template = sys.argv[1]
    path_out_env_header = sys.argv[2]
    # Prepare the runtime environment variables.
    env = invoke_printchplenv_wrapper()
    # Read in the contents of the template file.
    with open(path_template, "r") as fp:
        template_str = fp.read()
    # Generate the env header.
    output = generate_env_header_str(env, template_str)
    with open(path_out_env_header, "w") as fp:
        fp.write(output)


if __name__ == "__main__":
    main()
