/*
 * Copyright 2020-2026 Hewlett Packard Enterprise Development LP
 * Copyright 2004-2019 Cray Inc.
 * Other additional copyright holders may be indicated within.
 *
 * The entirety of this work is licensed under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "chpl-prginfo.h"
#include <cstdio>
#include <string>
#include <sstream>

#define STR_INNER(x__) #x__
#define STR(x__) STR_INNER(x__)

#define CALLBACK_TYPE(ret_type__, ...) ret_type__ (*)(__VA_ARGS__)

const char* module_name = "ChapelSetProgramInfoDataEntries";
const char* setter_name = "chpl_setProgramInfoDataEntriesHere";
const char* formal_name = "prg";
const char* program_type = "chpl_programInfo";

static std::string get_typedef_name(const char* symbol) {
  std::stringstream ss;
  ss << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_PREFIX) << symbol
     << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_SUFFIX);
  return ss.str();
}

static std::string get_fnptr_type(const char* name, const char* ret_type,
                                  const char* formals) {
  std::stringstream ss;
  ss << ret_type << " (*" << name << ")(" << formals << ")";
  return ss.str();
}

static void expand_constant(FILE* fp, int indent, const char* name,
                            const char* type) {
  auto tdef = get_typedef_name(name);
  fprintf(fp, "%*s// C symbol: '%s %s'\n", indent, "", type, name);
  fprintf(fp, "%*sextern type %s;\n", indent, "", tdef.c_str());
  fprintf(fp, "%*sextern const %s: %s;\n", indent, "", name, tdef.c_str());
  fprintf(fp, "%*s%s.setConstant(\'%s\', %s);\n", indent, "",
              formal_name, name, name);
}

static void expand_callback(FILE* fp, int indent, const char* name,
                            const char* ret_type,
                            const char* formals) {
  auto fntype = get_fnptr_type(name, ret_type, formals);
  fprintf(fp, "%*s// C symbol: '%s'\n", indent, "", fntype.c_str());
  fprintf(fp, "%*s%s.setCallback(\'%s\');\n", indent, "", formal_name, name);
}

static void print_setter_proc(FILE* fp, int indent) {
  fprintf(fp, "%*sproc %s(ref %s: %s) {\n", indent, "",
              setter_name,
              formal_name,
              program_type);

  #define E_CONSTANT(name__, type__) do { \
    expand_constant(fp, indent+2, #name__, #type__); \
  } while (0);

  #define E_CALLBACK(name__, ret_type__, ...) do { \
    expand_callback(fp, indent+2, #name__, #ret_type__, #__VA_ARGS__); \
  } while (0);

  #include "chpl-prginfo-data-macro-adapter.h"

  fprintf(fp, "%*s}\n", indent, "");
}

static void print_global_decls(FILE* fp, int indent) {
  fprintf(fp, "%*suse ChapelProgramRegistration;\n", indent, "");
}

static void print_module_code(FILE* fp) {
  fprintf(fp, "// This module was automatically generated by a script.\n");
  fprintf(fp, "module %s {\n", module_name);
  print_global_decls(fp, 2);
  print_setter_proc(fp, 2);
  fprintf(fp, "}");
}

int main(int argc, const char** argv) {
  if (argc != 2) {
    fprintf(stderr, "Expected exactly 1 argument: a file path to write to\n");
    return 1;
  }

  auto path = argv[1];
  auto fp = fopen(path, "w");

  if (fp == nullptr || errno) {
    fprintf(stderr, "Failed to open %s\n", path);
    return 1;
  }

  print_module_code(fp);

  fclose(fp);

  return 0;
}
