#!/usr/bin/env python3

import optparse
import os
import re
import sys

# Gain access to the scripts in '$CHPL_HOME/util/chplenv'.
script_dir = os.path.dirname(os.path.realpath(__file__))
chpl_home_dir = os.path.dirname(os.path.dirname(script_dir))
chplenv_dir = os.path.join(chpl_home_dir, "util", "chplenv")
sys.path.insert(0, os.path.abspath(chplenv_dir))

import printchplenv

def invoke_printchplenv_wrapper():
  # Populate ENV_VALS as 'main' does in 'printchplenv.py'...
  printchplenv.compute_all_values()
  # This is the exact set of arguments needed to match the following:
  # printchplenv --runtime --no-tidy --anonymize --simple
  got = printchplenv.printchplenv(contents=set(['runtime']),
                                  print_filters=set(['anonymize']),
                                  print_format='simple',
                                  only=None,
                                  raw=False)
  ret = {}
  for line in got.split('\n'):
    parts = line.split('=', maxsplit=1)
    if not line or not parts: continue
    assert(len(parts) == 2)
    k = parts[0].strip()
    v = parts[1].strip()
    ret[k] = v
  return ret

def generate_env_defines():
  env = invoke_printchplenv_wrapper()
  ret = '// Macros to use in preprocessor \'#if\' directives...\n'
  for k, v in env.items():
    # Replace any character that is not a letter, number, or underscore.
    macro_name = re.sub(r'[^a-zA-Z0-9_]', '_', v).upper()
    ret += '#define ' + '_'.join((k.upper(), macro_name)) + '\n'
  ret += '// Macro constants to use with \'strcmp\'...\n'
  for k, v in env.items():
    macro_name = k.upper() + '_RT'
    ret += ' '.join(('#define', macro_name, f'\"{v}\"')) + '\n'
  return ret

def generate_env_header_str(template_str):
  ret = template_str
  ret += '/* THIS FILE IS AUTOMATICALLY GENERATED */\n'
  ret += '#ifndef _CHPL_ENV_GEN_H_\n'
  ret += '#define _CHPL_ENV_GEN_H_\n'
  ret += generate_env_defines()
  ret += '#endif /* _CHPL_ENV_GEN_H_ */'
  return ret

# Argument (1) is the path to the template file.
# Argument (2) is the output path.
def main():
  if len(sys.argv) > 3:
    print('Expected exactly two arguments!', f=stderr)
    return
  path_template = sys.argv[1]
  path_out = sys.argv[2]
  with open(path_template, 'r') as fp:
    template = fp.read()
  output = generate_env_header_str(template)
  with open(path_out, 'w') as fp:
    fp.write(output)

if __name__ == "__main__":
    main()
