//
// This C++ program uses runtime headers in order to generate a Chapel
// module which prepares the data entries of a 'chpl_rt_prginfo'
// struct on a given locale. The entries can be found in the runtime
// header 'chpl-prginfo-data-macro.h'.
//
// The module contents currently do not vary based on the Chapel
// configuration, so the output directory does not need a cfg-based
// prefix.
//

#include "chpl-prginfo.h"
#include <fstream>
#include <iostream>
#include <string>

#define STR_INNER(x__) #x__
#define STR(x__) STR_INNER(x__)
#define INDENT(n__) std::string(n__, ' ')

#define CALLBACK_TYPE(ret_type__, ...) ret_type__ (*)(__VA_ARGS__)

const char* module_name = "ChapelSetProgramInfoDataEntries";
const char* setter_name = "chpl_setProgramInfoDataEntriesHere";
const char* formal_name = "prg";
const char* program_type = "chpl_programInfo";

static std::ofstream& out_typedef_name(std::ofstream& ofs,
                                       const char* symbol) {
  ofs << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_PREFIX) << symbol
      << STR(CHPL_RT_PRGINFO_DATA_ENTRY_TYPE_SUFFIX);
  return ofs;
}

static std::ofstream& out_fnptr_type(std::ofstream& ofs,
                                     const char* name,
                                     const char* ret_type,
                                     const char* formals) {
  ofs << ret_type << " (*" << name << ")(" << formals << ")";
  return ofs;
}

static void expand_constant(std::ofstream& ofs, int indent,
                            const char* name,
                            const char* type) {
  ofs << INDENT(indent);
  ofs << "// C symbol: '" << type << " " << name << "'\n";
  ofs << INDENT(indent);
  ofs << "extern type ";
  out_typedef_name(ofs, name) << ";\n";
  ofs << INDENT(indent);
  ofs << "extern const " << name << ": ";
  out_typedef_name(ofs, name) << ";\n";
  ofs << INDENT(indent);
  ofs << formal_name << ".setConstant(\'" << name << "\', " << name;
  ofs << ");\n";
}

static void expand_callback(std::ofstream& ofs, int indent,
                            const char* name,
                            const char* ret_type,
                            const char* formals) {
  ofs << INDENT(indent);
  ofs << "// C symbol: '";
  out_fnptr_type(ofs, name, ret_type, formals) << "'\n";
  ofs << INDENT(indent);
  ofs << formal_name << ".setCallback(\'" << name << "\');\n";
}

static void print_setter_proc(std::ofstream& ofs, int indent) {
  ofs << INDENT(indent);
  ofs << "proc " << setter_name << "(ref " << formal_name << ": ";
  ofs << program_type << ") {\n";

  #define E_CONSTANT(name__, type__) do { \
    expand_constant(ofs, indent+2, #name__, #type__); \
  } while (0);

  #define E_CALLBACK(name__, ret_type__, ...) do { \
    expand_callback(ofs, indent+2, #name__, #ret_type__, #__VA_ARGS__); \
  } while (0);

  #include "chpl-prginfo-data-macro-adapter.h"

  ofs << INDENT(indent);
  ofs << "}\n";
}

static void print_global_decls(std::ofstream& ofs, int indent) {
  ofs << INDENT(indent);
  ofs << "use ChapelProgramRegistration;\n";
}

static void print_module_code(std::ofstream& ofs) {
  ofs << "// This module was automatically generated by a script.\n";
  ofs << "module " << module_name << " {\n";
  print_global_decls(ofs, 2);
  print_setter_proc(ofs, 2);
  ofs << "}";
}

int main(int argc, const char** argv) {
  if (argc != 2) {
    std::cerr << "Expected 1 argument: a writeable file path" << std::endl;
    return 1;
  }

  auto path = argv[1];
  std::ofstream ofs(path);

  if (!ofs.is_open()) {
    std::cerr << "Failed to open '" << path << "'" << std::endl;
    return 1;
  }

  print_module_code(ofs);

  ofs.close();

  return 0;
}
