#!/bin/bash

set -e

# Note: This is not safe for parallel testing

# Only run this script when doing a perf run
if [ -n "$CHPL_TEST_PERF" ]; then

  if [ ! -d $CHPL_HOME/test/tmp ]; then
    mkdir $CHPL_HOME/test/tmp
  fi

  if [ ! -f $CHPL_HOME/test/tmp/fasta.big ]; then
    # '$3' is the compiler given to us by sub_test
    $3 $CHPL_HOME/test/studies/shootout/fasta/kbrady/fasta-printf.chpl --fast -o tmpFasta
    
    # needed by k-nucleotide and reverse-complement
    ./tmpFasta --n=25000000 > $CHPL_HOME/test/tmp/fasta.big

    # needed by regex-dna
    ./tmpFasta --n=5000000 > $CHPL_HOME/test/tmp/fasta.mid

    rm ./tmpFasta
  fi
fi
