#
# CHPL_MAKE_PLATFORM stuff
#
#
# CHPL_MAKE_PLATFORM is simply the one-word description we'll use for
# all platforms that we run on.  The long name is being used to avoid
# PLATFORM which is sometimes set by shell environments.
#
CHPL_MAKE_PLATFORM = $(shell $(CHAPEL_ROOT)/util/platform.pl)
