#!/usr/bin/env python

import sys, os, shutil, string;

testname=sys.argv[1]
compopts=sys.argv[4]

chpl_comm = os.getenv('CHPL_COMM')
if chpl_comm=='none' or chpl_comm==None:
    dist = 'default'
else:
    dist = 'block'

searchstring='distType=DistType.'
s = string.rfind(compopts, searchstring)

if s != -1:
    opt = compopts[s+len(searchstring):len(compopts)]
    dist = opt.split()[0]

commlayer=os.getenv('CHPL_COMM')
if dist=='cyclic' and commlayer!=None and commlayer!='none':
    # This is going to fail to perform the optimized on due to a halt
    # statement in chpl__diffMod().
    goodfn=testname+'.comm-none.good'
    if os.path.isfile(goodfn):
        shutil.copy(goodfn, testname+'.comm-'+commlayer+'.good')
