#define CHPL_COMPILER_LIB_VERSION_MAJOR @CHPL_MAJOR_VERSION@
#define CHPL_COMPILER_LIB_VERSION_MINOR @CHPL_MINOR_VERSION@
#define CHPL_COMPILER_LIB_VERSION_PATCH @CHPL_PATCH_VERSION@
#define CHPL_CONFIGURED_PREFIX "@CMAKE_INSTALL_PREFIX@"
#define CHPL_BUILD_VERSION "@CHPL_BUILD_VERSION@"
#define CHPL_OFFICIAL_RELEASE @CHPL_OFFICIAL_RELEASE@
