#define CHPL_COMPILER_LIB_VERSION_MAJOR @libdyno_VERSION_MAJOR@
#define CHPL_COMPILER_LIB_VERSION_MINOR @libdyno_VERSION_MINOR@

/* this might be "reasonable" */
#define CONFIGURE_PREFIX "@CMAKE_INSTALL_PREFIX@"
