#!/usr/bin/env bash

if command -v lldb >/dev/null ; then

  # Sept 10, 2025: skip if lldb does not have python support
  # required for pretty printing which affects the output of the tests
  python_path=$(lldb --python-path 2>/dev/null)
  if [[ -z "$python_path" || ! -x "$python_path" ]]; then
    echo "True"
  else
    echo "False"
  fi
else
  echo "True"
fi
