03-error-in-fun.chpl:81: In function 'funBlank':
03-error-in-fun.chpl:118: error: illegal lvalue in assignment
03-error-in-fun.chpl:119: error: illegal lvalue in assignment
03-error-in-fun.chpl:120: error: illegal lvalue in assignment
03-error-in-fun.chpl:121: error: illegal lvalue in assignment
03-error-in-fun.chpl:122: error: illegal lvalue in assignment
03-error-in-fun.chpl:123: error: illegal lvalue in assignment
03-error-in-fun.chpl:124: error: illegal lvalue in assignment
03-error-in-fun.chpl:125: error: illegal lvalue in assignment
03-error-in-fun.chpl:126: error: illegal lvalue in assignment
03-error-in-fun.chpl:127: error: illegal lvalue in assignment
03-error-in-fun.chpl:128: error: illegal lvalue in assignment
03-error-in-fun.chpl:129: error: illegal lvalue in assignment
03-error-in-fun.chpl:130: error: illegal lvalue in assignment
03-error-in-fun.chpl:131: error: illegal lvalue in assignment
03-error-in-fun.chpl:132: error: illegal lvalue in assignment
03-error-in-fun.chpl:133: error: illegal lvalue in assignment
03-error-in-fun.chpl:134: error: illegal lvalue in assignment
03-error-in-fun.chpl:135: error: illegal lvalue in assignment
03-error-in-fun.chpl:136: error: illegal lvalue in assignment
03-error-in-fun.chpl:137: error: illegal lvalue in assignment
03-error-in-fun.chpl:138: error: illegal lvalue in assignment
03-error-in-fun.chpl:139: error: illegal lvalue in assignment
03-error-in-fun.chpl:140: error: illegal lvalue in assignment
03-error-in-fun.chpl:141: error: illegal lvalue in assignment
03-error-in-fun.chpl:142: error: illegal lvalue in assignment
03-error-in-fun.chpl:151: error: illegal lvalue in assignment
03-error-in-fun.chpl:152: error: illegal lvalue in assignment
03-error-in-fun.chpl:153: error: illegal lvalue in assignment
03-error-in-fun.chpl:154: error: illegal lvalue in assignment
03-error-in-fun.chpl:155: error: illegal lvalue in assignment
03-error-in-fun.chpl:156: error: illegal lvalue in assignment
03-error-in-fun.chpl:157: error: illegal lvalue in assignment
03-error-in-fun.chpl:158: error: illegal lvalue in assignment
03-error-in-fun.chpl:159: error: illegal lvalue in assignment
03-error-in-fun.chpl:160: error: illegal lvalue in assignment
03-error-in-fun.chpl:161: error: illegal lvalue in assignment
03-error-in-fun.chpl:162: error: illegal lvalue in assignment
03-error-in-fun.chpl:163: error: illegal lvalue in assignment
03-error-in-fun.chpl:164: error: illegal lvalue in assignment
03-error-in-fun.chpl:165: error: illegal lvalue in assignment
03-error-in-fun.chpl:166: error: illegal lvalue in assignment
03-error-in-fun.chpl:167: error: illegal lvalue in assignment
03-error-in-fun.chpl:168: error: illegal lvalue in assignment
03-error-in-fun.chpl:169: error: illegal lvalue in assignment
03-error-in-fun.chpl:170: error: illegal lvalue in assignment
03-error-in-fun.chpl:171: error: illegal lvalue in assignment
03-error-in-fun.chpl:172: error: illegal lvalue in assignment
03-error-in-fun.chpl:173: error: illegal lvalue in assignment
03-error-in-fun.chpl:174: error: illegal lvalue in assignment
03-error-in-fun.chpl:175: error: illegal lvalue in assignment
03-error-in-fun.chpl:184: error: illegal lvalue in assignment
03-error-in-fun.chpl:185: error: illegal lvalue in assignment
03-error-in-fun.chpl:186: error: illegal lvalue in assignment
03-error-in-fun.chpl:187: error: illegal lvalue in assignment
03-error-in-fun.chpl:188: error: illegal lvalue in assignment
03-error-in-fun.chpl:189: error: illegal lvalue in assignment
03-error-in-fun.chpl:190: error: illegal lvalue in assignment
03-error-in-fun.chpl:191: error: illegal lvalue in assignment
03-error-in-fun.chpl:192: error: illegal lvalue in assignment
03-error-in-fun.chpl:193: error: illegal lvalue in assignment
03-error-in-fun.chpl:194: error: illegal lvalue in assignment
03-error-in-fun.chpl:195: error: illegal lvalue in assignment
03-error-in-fun.chpl:196: error: illegal lvalue in assignment
03-error-in-fun.chpl:197: error: illegal lvalue in assignment
03-error-in-fun.chpl:198: error: illegal lvalue in assignment
03-error-in-fun.chpl:199: error: illegal lvalue in assignment
03-error-in-fun.chpl:200: error: illegal lvalue in assignment
03-error-in-fun.chpl:201: error: illegal lvalue in assignment
03-error-in-fun.chpl:202: error: illegal lvalue in assignment
03-error-in-fun.chpl:203: error: illegal lvalue in assignment
03-error-in-fun.chpl:204: error: illegal lvalue in assignment
03-error-in-fun.chpl:205: error: illegal lvalue in assignment
03-error-in-fun.chpl:206: error: illegal lvalue in assignment
03-error-in-fun.chpl:207: error: illegal lvalue in assignment
03-error-in-fun.chpl:208: error: illegal lvalue in assignment
03-error-in-fun.chpl:256: In function 'funConst':
03-error-in-fun.chpl:293: error: illegal lvalue in assignment
03-error-in-fun.chpl:294: error: illegal lvalue in assignment
03-error-in-fun.chpl:295: error: illegal lvalue in assignment
03-error-in-fun.chpl:296: error: illegal lvalue in assignment
03-error-in-fun.chpl:297: error: illegal lvalue in assignment
03-error-in-fun.chpl:298: error: illegal lvalue in assignment
03-error-in-fun.chpl:299: error: illegal lvalue in assignment
03-error-in-fun.chpl:300: error: illegal lvalue in assignment
03-error-in-fun.chpl:301: error: illegal lvalue in assignment
03-error-in-fun.chpl:302: error: illegal lvalue in assignment
03-error-in-fun.chpl:303: error: illegal lvalue in assignment
03-error-in-fun.chpl:304: error: illegal lvalue in assignment
03-error-in-fun.chpl:305: error: illegal lvalue in assignment
03-error-in-fun.chpl:306: error: illegal lvalue in assignment
03-error-in-fun.chpl:307: error: illegal lvalue in assignment
03-error-in-fun.chpl:308: error: illegal lvalue in assignment
03-error-in-fun.chpl:309: error: illegal lvalue in assignment
03-error-in-fun.chpl:310: error: illegal lvalue in assignment
03-error-in-fun.chpl:311: error: illegal lvalue in assignment
03-error-in-fun.chpl:312: error: illegal lvalue in assignment
03-error-in-fun.chpl:313: error: illegal lvalue in assignment
03-error-in-fun.chpl:314: error: illegal lvalue in assignment
03-error-in-fun.chpl:315: error: illegal lvalue in assignment
03-error-in-fun.chpl:316: error: illegal lvalue in assignment
03-error-in-fun.chpl:317: error: illegal lvalue in assignment
03-error-in-fun.chpl:326: error: illegal lvalue in assignment
03-error-in-fun.chpl:327: error: illegal lvalue in assignment
03-error-in-fun.chpl:328: error: illegal lvalue in assignment
03-error-in-fun.chpl:329: error: illegal lvalue in assignment
03-error-in-fun.chpl:330: error: illegal lvalue in assignment
03-error-in-fun.chpl:331: error: illegal lvalue in assignment
03-error-in-fun.chpl:332: error: illegal lvalue in assignment
03-error-in-fun.chpl:333: error: illegal lvalue in assignment
03-error-in-fun.chpl:334: error: illegal lvalue in assignment
03-error-in-fun.chpl:335: error: illegal lvalue in assignment
03-error-in-fun.chpl:336: error: illegal lvalue in assignment
03-error-in-fun.chpl:337: error: illegal lvalue in assignment
03-error-in-fun.chpl:338: error: illegal lvalue in assignment
03-error-in-fun.chpl:339: error: illegal lvalue in assignment
03-error-in-fun.chpl:340: error: illegal lvalue in assignment
03-error-in-fun.chpl:341: error: illegal lvalue in assignment
03-error-in-fun.chpl:342: error: illegal lvalue in assignment
03-error-in-fun.chpl:343: error: illegal lvalue in assignment
03-error-in-fun.chpl:344: error: illegal lvalue in assignment
03-error-in-fun.chpl:345: error: illegal lvalue in assignment
03-error-in-fun.chpl:346: error: illegal lvalue in assignment
03-error-in-fun.chpl:347: error: illegal lvalue in assignment
03-error-in-fun.chpl:348: error: illegal lvalue in assignment
03-error-in-fun.chpl:349: error: illegal lvalue in assignment
03-error-in-fun.chpl:350: error: illegal lvalue in assignment
03-error-in-fun.chpl:359: error: illegal lvalue in assignment
03-error-in-fun.chpl:360: error: illegal lvalue in assignment
03-error-in-fun.chpl:361: error: illegal lvalue in assignment
03-error-in-fun.chpl:362: error: illegal lvalue in assignment
03-error-in-fun.chpl:363: error: illegal lvalue in assignment
03-error-in-fun.chpl:364: error: illegal lvalue in assignment
03-error-in-fun.chpl:365: error: illegal lvalue in assignment
03-error-in-fun.chpl:366: error: illegal lvalue in assignment
03-error-in-fun.chpl:367: error: illegal lvalue in assignment
03-error-in-fun.chpl:368: error: illegal lvalue in assignment
03-error-in-fun.chpl:369: error: illegal lvalue in assignment
03-error-in-fun.chpl:370: error: illegal lvalue in assignment
03-error-in-fun.chpl:371: error: illegal lvalue in assignment
03-error-in-fun.chpl:372: error: illegal lvalue in assignment
03-error-in-fun.chpl:373: error: illegal lvalue in assignment
03-error-in-fun.chpl:374: error: illegal lvalue in assignment
03-error-in-fun.chpl:375: error: illegal lvalue in assignment
03-error-in-fun.chpl:376: error: illegal lvalue in assignment
03-error-in-fun.chpl:377: error: illegal lvalue in assignment
03-error-in-fun.chpl:378: error: illegal lvalue in assignment
03-error-in-fun.chpl:379: error: illegal lvalue in assignment
03-error-in-fun.chpl:380: error: illegal lvalue in assignment
03-error-in-fun.chpl:381: error: illegal lvalue in assignment
03-error-in-fun.chpl:382: error: illegal lvalue in assignment
03-error-in-fun.chpl:383: error: illegal lvalue in assignment
03-error-in-fun.chpl:431: In function 'funConstIn':
03-error-in-fun.chpl:468: error: illegal lvalue in assignment
03-error-in-fun.chpl:469: error: illegal lvalue in assignment
03-error-in-fun.chpl:470: error: illegal lvalue in assignment
03-error-in-fun.chpl:471: error: illegal lvalue in assignment
03-error-in-fun.chpl:472: error: illegal lvalue in assignment
03-error-in-fun.chpl:473: error: illegal lvalue in assignment
03-error-in-fun.chpl:474: error: illegal lvalue in assignment
03-error-in-fun.chpl:475: error: illegal lvalue in assignment
03-error-in-fun.chpl:476: error: illegal lvalue in assignment
03-error-in-fun.chpl:477: error: illegal lvalue in assignment
03-error-in-fun.chpl:478: error: illegal lvalue in assignment
03-error-in-fun.chpl:479: error: illegal lvalue in assignment
03-error-in-fun.chpl:480: error: illegal lvalue in assignment
03-error-in-fun.chpl:481: error: illegal lvalue in assignment
03-error-in-fun.chpl:482: error: illegal lvalue in assignment
03-error-in-fun.chpl:483: error: illegal lvalue in assignment
03-error-in-fun.chpl:484: error: illegal lvalue in assignment
03-error-in-fun.chpl:485: error: illegal lvalue in assignment
03-error-in-fun.chpl:486: error: illegal lvalue in assignment
03-error-in-fun.chpl:487: error: illegal lvalue in assignment
03-error-in-fun.chpl:488: error: illegal lvalue in assignment
03-error-in-fun.chpl:489: error: illegal lvalue in assignment
03-error-in-fun.chpl:490: error: illegal lvalue in assignment
03-error-in-fun.chpl:491: error: illegal lvalue in assignment
03-error-in-fun.chpl:492: error: illegal lvalue in assignment
03-error-in-fun.chpl:501: error: illegal lvalue in assignment
03-error-in-fun.chpl:502: error: illegal lvalue in assignment
03-error-in-fun.chpl:503: error: illegal lvalue in assignment
03-error-in-fun.chpl:504: error: illegal lvalue in assignment
03-error-in-fun.chpl:505: error: illegal lvalue in assignment
03-error-in-fun.chpl:506: error: illegal lvalue in assignment
03-error-in-fun.chpl:507: error: illegal lvalue in assignment
03-error-in-fun.chpl:508: error: illegal lvalue in assignment
03-error-in-fun.chpl:509: error: illegal lvalue in assignment
03-error-in-fun.chpl:510: error: illegal lvalue in assignment
03-error-in-fun.chpl:511: error: illegal lvalue in assignment
03-error-in-fun.chpl:512: error: illegal lvalue in assignment
03-error-in-fun.chpl:513: error: illegal lvalue in assignment
03-error-in-fun.chpl:514: error: illegal lvalue in assignment
03-error-in-fun.chpl:515: error: illegal lvalue in assignment
03-error-in-fun.chpl:516: error: illegal lvalue in assignment
03-error-in-fun.chpl:517: error: illegal lvalue in assignment
03-error-in-fun.chpl:518: error: illegal lvalue in assignment
03-error-in-fun.chpl:519: error: illegal lvalue in assignment
03-error-in-fun.chpl:520: error: illegal lvalue in assignment
03-error-in-fun.chpl:521: error: illegal lvalue in assignment
03-error-in-fun.chpl:522: error: illegal lvalue in assignment
03-error-in-fun.chpl:523: error: illegal lvalue in assignment
03-error-in-fun.chpl:524: error: illegal lvalue in assignment
03-error-in-fun.chpl:525: error: illegal lvalue in assignment
03-error-in-fun.chpl:534: error: illegal lvalue in assignment
03-error-in-fun.chpl:535: error: illegal lvalue in assignment
03-error-in-fun.chpl:536: error: illegal lvalue in assignment
03-error-in-fun.chpl:537: error: illegal lvalue in assignment
03-error-in-fun.chpl:538: error: illegal lvalue in assignment
03-error-in-fun.chpl:539: error: illegal lvalue in assignment
03-error-in-fun.chpl:540: error: illegal lvalue in assignment
03-error-in-fun.chpl:541: error: illegal lvalue in assignment
03-error-in-fun.chpl:542: error: illegal lvalue in assignment
03-error-in-fun.chpl:543: error: illegal lvalue in assignment
03-error-in-fun.chpl:544: error: illegal lvalue in assignment
03-error-in-fun.chpl:545: error: illegal lvalue in assignment
03-error-in-fun.chpl:546: error: illegal lvalue in assignment
03-error-in-fun.chpl:547: error: illegal lvalue in assignment
03-error-in-fun.chpl:548: error: illegal lvalue in assignment
03-error-in-fun.chpl:549: error: illegal lvalue in assignment
03-error-in-fun.chpl:550: error: illegal lvalue in assignment
03-error-in-fun.chpl:551: error: illegal lvalue in assignment
03-error-in-fun.chpl:552: error: illegal lvalue in assignment
03-error-in-fun.chpl:553: error: illegal lvalue in assignment
03-error-in-fun.chpl:554: error: illegal lvalue in assignment
03-error-in-fun.chpl:555: error: illegal lvalue in assignment
03-error-in-fun.chpl:556: error: illegal lvalue in assignment
03-error-in-fun.chpl:557: error: illegal lvalue in assignment
03-error-in-fun.chpl:558: error: illegal lvalue in assignment
03-error-in-fun.chpl:606: In function 'funIn':
03-error-in-fun.chpl:643: error: illegal lvalue in assignment
03-error-in-fun.chpl:644: error: illegal lvalue in assignment
03-error-in-fun.chpl:645: error: illegal lvalue in assignment
03-error-in-fun.chpl:646: error: illegal lvalue in assignment
03-error-in-fun.chpl:647: error: illegal lvalue in assignment
03-error-in-fun.chpl:648: error: illegal lvalue in assignment
03-error-in-fun.chpl:649: error: illegal lvalue in assignment
03-error-in-fun.chpl:650: error: illegal lvalue in assignment
03-error-in-fun.chpl:651: error: illegal lvalue in assignment
03-error-in-fun.chpl:652: error: illegal lvalue in assignment
03-error-in-fun.chpl:653: error: illegal lvalue in assignment
03-error-in-fun.chpl:654: error: illegal lvalue in assignment
03-error-in-fun.chpl:655: error: illegal lvalue in assignment
03-error-in-fun.chpl:656: error: illegal lvalue in assignment
03-error-in-fun.chpl:657: error: illegal lvalue in assignment
03-error-in-fun.chpl:658: error: illegal lvalue in assignment
03-error-in-fun.chpl:659: error: illegal lvalue in assignment
03-error-in-fun.chpl:660: error: illegal lvalue in assignment
03-error-in-fun.chpl:661: error: illegal lvalue in assignment
03-error-in-fun.chpl:662: error: illegal lvalue in assignment
03-error-in-fun.chpl:663: error: illegal lvalue in assignment
03-error-in-fun.chpl:664: error: illegal lvalue in assignment
03-error-in-fun.chpl:665: error: illegal lvalue in assignment
03-error-in-fun.chpl:666: error: illegal lvalue in assignment
03-error-in-fun.chpl:667: error: illegal lvalue in assignment
03-error-in-fun.chpl:676: error: illegal lvalue in assignment
03-error-in-fun.chpl:677: error: illegal lvalue in assignment
03-error-in-fun.chpl:678: error: illegal lvalue in assignment
03-error-in-fun.chpl:679: error: illegal lvalue in assignment
03-error-in-fun.chpl:680: error: illegal lvalue in assignment
03-error-in-fun.chpl:681: error: illegal lvalue in assignment
03-error-in-fun.chpl:682: error: illegal lvalue in assignment
03-error-in-fun.chpl:683: error: illegal lvalue in assignment
03-error-in-fun.chpl:684: error: illegal lvalue in assignment
03-error-in-fun.chpl:685: error: illegal lvalue in assignment
03-error-in-fun.chpl:686: error: illegal lvalue in assignment
03-error-in-fun.chpl:687: error: illegal lvalue in assignment
03-error-in-fun.chpl:688: error: illegal lvalue in assignment
03-error-in-fun.chpl:689: error: illegal lvalue in assignment
03-error-in-fun.chpl:690: error: illegal lvalue in assignment
03-error-in-fun.chpl:691: error: illegal lvalue in assignment
03-error-in-fun.chpl:692: error: illegal lvalue in assignment
03-error-in-fun.chpl:693: error: illegal lvalue in assignment
03-error-in-fun.chpl:694: error: illegal lvalue in assignment
03-error-in-fun.chpl:695: error: illegal lvalue in assignment
03-error-in-fun.chpl:696: error: illegal lvalue in assignment
03-error-in-fun.chpl:697: error: illegal lvalue in assignment
03-error-in-fun.chpl:698: error: illegal lvalue in assignment
03-error-in-fun.chpl:699: error: illegal lvalue in assignment
03-error-in-fun.chpl:700: error: illegal lvalue in assignment
03-error-in-fun.chpl:709: error: illegal lvalue in assignment
03-error-in-fun.chpl:710: error: illegal lvalue in assignment
03-error-in-fun.chpl:711: error: illegal lvalue in assignment
03-error-in-fun.chpl:712: error: illegal lvalue in assignment
03-error-in-fun.chpl:713: error: illegal lvalue in assignment
03-error-in-fun.chpl:714: error: illegal lvalue in assignment
03-error-in-fun.chpl:715: error: illegal lvalue in assignment
03-error-in-fun.chpl:716: error: illegal lvalue in assignment
03-error-in-fun.chpl:717: error: illegal lvalue in assignment
03-error-in-fun.chpl:718: error: illegal lvalue in assignment
03-error-in-fun.chpl:719: error: illegal lvalue in assignment
03-error-in-fun.chpl:720: error: illegal lvalue in assignment
03-error-in-fun.chpl:721: error: illegal lvalue in assignment
03-error-in-fun.chpl:722: error: illegal lvalue in assignment
03-error-in-fun.chpl:723: error: illegal lvalue in assignment
03-error-in-fun.chpl:724: error: illegal lvalue in assignment
03-error-in-fun.chpl:725: error: illegal lvalue in assignment
03-error-in-fun.chpl:726: error: illegal lvalue in assignment
03-error-in-fun.chpl:727: error: illegal lvalue in assignment
03-error-in-fun.chpl:728: error: illegal lvalue in assignment
03-error-in-fun.chpl:729: error: illegal lvalue in assignment
03-error-in-fun.chpl:730: error: illegal lvalue in assignment
03-error-in-fun.chpl:731: error: illegal lvalue in assignment
03-error-in-fun.chpl:732: error: illegal lvalue in assignment
03-error-in-fun.chpl:733: error: illegal lvalue in assignment
03-error-in-fun.chpl:781: In function 'funInOut':
03-error-in-fun.chpl:818: error: illegal lvalue in assignment
03-error-in-fun.chpl:819: error: illegal lvalue in assignment
03-error-in-fun.chpl:820: error: illegal lvalue in assignment
03-error-in-fun.chpl:821: error: illegal lvalue in assignment
03-error-in-fun.chpl:822: error: illegal lvalue in assignment
03-error-in-fun.chpl:823: error: illegal lvalue in assignment
03-error-in-fun.chpl:824: error: illegal lvalue in assignment
03-error-in-fun.chpl:825: error: illegal lvalue in assignment
03-error-in-fun.chpl:826: error: illegal lvalue in assignment
03-error-in-fun.chpl:827: error: illegal lvalue in assignment
03-error-in-fun.chpl:828: error: illegal lvalue in assignment
03-error-in-fun.chpl:829: error: illegal lvalue in assignment
03-error-in-fun.chpl:830: error: illegal lvalue in assignment
03-error-in-fun.chpl:831: error: illegal lvalue in assignment
03-error-in-fun.chpl:832: error: illegal lvalue in assignment
03-error-in-fun.chpl:833: error: illegal lvalue in assignment
03-error-in-fun.chpl:834: error: illegal lvalue in assignment
03-error-in-fun.chpl:835: error: illegal lvalue in assignment
03-error-in-fun.chpl:836: error: illegal lvalue in assignment
03-error-in-fun.chpl:837: error: illegal lvalue in assignment
03-error-in-fun.chpl:838: error: illegal lvalue in assignment
03-error-in-fun.chpl:839: error: illegal lvalue in assignment
03-error-in-fun.chpl:840: error: illegal lvalue in assignment
03-error-in-fun.chpl:841: error: illegal lvalue in assignment
03-error-in-fun.chpl:842: error: illegal lvalue in assignment
03-error-in-fun.chpl:851: error: illegal lvalue in assignment
03-error-in-fun.chpl:852: error: illegal lvalue in assignment
03-error-in-fun.chpl:853: error: illegal lvalue in assignment
03-error-in-fun.chpl:854: error: illegal lvalue in assignment
03-error-in-fun.chpl:855: error: illegal lvalue in assignment
03-error-in-fun.chpl:856: error: illegal lvalue in assignment
03-error-in-fun.chpl:857: error: illegal lvalue in assignment
03-error-in-fun.chpl:858: error: illegal lvalue in assignment
03-error-in-fun.chpl:859: error: illegal lvalue in assignment
03-error-in-fun.chpl:860: error: illegal lvalue in assignment
03-error-in-fun.chpl:861: error: illegal lvalue in assignment
03-error-in-fun.chpl:862: error: illegal lvalue in assignment
03-error-in-fun.chpl:863: error: illegal lvalue in assignment
03-error-in-fun.chpl:864: error: illegal lvalue in assignment
03-error-in-fun.chpl:865: error: illegal lvalue in assignment
03-error-in-fun.chpl:866: error: illegal lvalue in assignment
03-error-in-fun.chpl:867: error: illegal lvalue in assignment
03-error-in-fun.chpl:868: error: illegal lvalue in assignment
03-error-in-fun.chpl:869: error: illegal lvalue in assignment
03-error-in-fun.chpl:870: error: illegal lvalue in assignment
03-error-in-fun.chpl:871: error: illegal lvalue in assignment
03-error-in-fun.chpl:872: error: illegal lvalue in assignment
03-error-in-fun.chpl:873: error: illegal lvalue in assignment
03-error-in-fun.chpl:874: error: illegal lvalue in assignment
03-error-in-fun.chpl:875: error: illegal lvalue in assignment
03-error-in-fun.chpl:884: error: illegal lvalue in assignment
03-error-in-fun.chpl:885: error: illegal lvalue in assignment
03-error-in-fun.chpl:886: error: illegal lvalue in assignment
03-error-in-fun.chpl:887: error: illegal lvalue in assignment
03-error-in-fun.chpl:888: error: illegal lvalue in assignment
03-error-in-fun.chpl:889: error: illegal lvalue in assignment
03-error-in-fun.chpl:890: error: illegal lvalue in assignment
03-error-in-fun.chpl:891: error: illegal lvalue in assignment
03-error-in-fun.chpl:892: error: illegal lvalue in assignment
03-error-in-fun.chpl:893: error: illegal lvalue in assignment
03-error-in-fun.chpl:894: error: illegal lvalue in assignment
03-error-in-fun.chpl:895: error: illegal lvalue in assignment
03-error-in-fun.chpl:896: error: illegal lvalue in assignment
03-error-in-fun.chpl:897: error: illegal lvalue in assignment
03-error-in-fun.chpl:898: error: illegal lvalue in assignment
03-error-in-fun.chpl:899: error: illegal lvalue in assignment
03-error-in-fun.chpl:900: error: illegal lvalue in assignment
03-error-in-fun.chpl:901: error: illegal lvalue in assignment
03-error-in-fun.chpl:902: error: illegal lvalue in assignment
03-error-in-fun.chpl:903: error: illegal lvalue in assignment
03-error-in-fun.chpl:904: error: illegal lvalue in assignment
03-error-in-fun.chpl:905: error: illegal lvalue in assignment
03-error-in-fun.chpl:906: error: illegal lvalue in assignment
03-error-in-fun.chpl:907: error: illegal lvalue in assignment
03-error-in-fun.chpl:908: error: illegal lvalue in assignment
03-error-in-fun.chpl:956: In function 'funOut':
03-error-in-fun.chpl:993: error: illegal lvalue in assignment
03-error-in-fun.chpl:994: error: illegal lvalue in assignment
03-error-in-fun.chpl:995: error: illegal lvalue in assignment
03-error-in-fun.chpl:996: error: illegal lvalue in assignment
03-error-in-fun.chpl:997: error: illegal lvalue in assignment
03-error-in-fun.chpl:998: error: illegal lvalue in assignment
03-error-in-fun.chpl:999: error: illegal lvalue in assignment
03-error-in-fun.chpl:1000: error: illegal lvalue in assignment
03-error-in-fun.chpl:1001: error: illegal lvalue in assignment
03-error-in-fun.chpl:1002: error: illegal lvalue in assignment
03-error-in-fun.chpl:1003: error: illegal lvalue in assignment
03-error-in-fun.chpl:1004: error: illegal lvalue in assignment
03-error-in-fun.chpl:1005: error: illegal lvalue in assignment
03-error-in-fun.chpl:1006: error: illegal lvalue in assignment
03-error-in-fun.chpl:1007: error: illegal lvalue in assignment
03-error-in-fun.chpl:1008: error: illegal lvalue in assignment
03-error-in-fun.chpl:1009: error: illegal lvalue in assignment
03-error-in-fun.chpl:1010: error: illegal lvalue in assignment
03-error-in-fun.chpl:1011: error: illegal lvalue in assignment
03-error-in-fun.chpl:1012: error: illegal lvalue in assignment
03-error-in-fun.chpl:1013: error: illegal lvalue in assignment
03-error-in-fun.chpl:1014: error: illegal lvalue in assignment
03-error-in-fun.chpl:1015: error: illegal lvalue in assignment
03-error-in-fun.chpl:1016: error: illegal lvalue in assignment
03-error-in-fun.chpl:1017: error: illegal lvalue in assignment
03-error-in-fun.chpl:1026: error: illegal lvalue in assignment
03-error-in-fun.chpl:1027: error: illegal lvalue in assignment
03-error-in-fun.chpl:1028: error: illegal lvalue in assignment
03-error-in-fun.chpl:1029: error: illegal lvalue in assignment
03-error-in-fun.chpl:1030: error: illegal lvalue in assignment
03-error-in-fun.chpl:1031: error: illegal lvalue in assignment
03-error-in-fun.chpl:1032: error: illegal lvalue in assignment
03-error-in-fun.chpl:1033: error: illegal lvalue in assignment
03-error-in-fun.chpl:1034: error: illegal lvalue in assignment
03-error-in-fun.chpl:1035: error: illegal lvalue in assignment
03-error-in-fun.chpl:1036: error: illegal lvalue in assignment
03-error-in-fun.chpl:1037: error: illegal lvalue in assignment
03-error-in-fun.chpl:1038: error: illegal lvalue in assignment
03-error-in-fun.chpl:1039: error: illegal lvalue in assignment
03-error-in-fun.chpl:1040: error: illegal lvalue in assignment
03-error-in-fun.chpl:1041: error: illegal lvalue in assignment
03-error-in-fun.chpl:1042: error: illegal lvalue in assignment
03-error-in-fun.chpl:1043: error: illegal lvalue in assignment
03-error-in-fun.chpl:1044: error: illegal lvalue in assignment
03-error-in-fun.chpl:1045: error: illegal lvalue in assignment
03-error-in-fun.chpl:1046: error: illegal lvalue in assignment
03-error-in-fun.chpl:1047: error: illegal lvalue in assignment
03-error-in-fun.chpl:1048: error: illegal lvalue in assignment
03-error-in-fun.chpl:1049: error: illegal lvalue in assignment
03-error-in-fun.chpl:1050: error: illegal lvalue in assignment
03-error-in-fun.chpl:1059: error: illegal lvalue in assignment
03-error-in-fun.chpl:1060: error: illegal lvalue in assignment
03-error-in-fun.chpl:1061: error: illegal lvalue in assignment
03-error-in-fun.chpl:1062: error: illegal lvalue in assignment
03-error-in-fun.chpl:1063: error: illegal lvalue in assignment
03-error-in-fun.chpl:1064: error: illegal lvalue in assignment
03-error-in-fun.chpl:1065: error: illegal lvalue in assignment
03-error-in-fun.chpl:1066: error: illegal lvalue in assignment
03-error-in-fun.chpl:1067: error: illegal lvalue in assignment
03-error-in-fun.chpl:1068: error: illegal lvalue in assignment
03-error-in-fun.chpl:1069: error: illegal lvalue in assignment
03-error-in-fun.chpl:1070: error: illegal lvalue in assignment
03-error-in-fun.chpl:1071: error: illegal lvalue in assignment
03-error-in-fun.chpl:1072: error: illegal lvalue in assignment
03-error-in-fun.chpl:1073: error: illegal lvalue in assignment
03-error-in-fun.chpl:1074: error: illegal lvalue in assignment
03-error-in-fun.chpl:1075: error: illegal lvalue in assignment
03-error-in-fun.chpl:1076: error: illegal lvalue in assignment
03-error-in-fun.chpl:1077: error: illegal lvalue in assignment
03-error-in-fun.chpl:1078: error: illegal lvalue in assignment
03-error-in-fun.chpl:1079: error: illegal lvalue in assignment
03-error-in-fun.chpl:1080: error: illegal lvalue in assignment
03-error-in-fun.chpl:1081: error: illegal lvalue in assignment
03-error-in-fun.chpl:1082: error: illegal lvalue in assignment
03-error-in-fun.chpl:1083: error: illegal lvalue in assignment
03-error-in-fun.chpl:1131: In function 'funRef':
03-error-in-fun.chpl:1168: error: illegal lvalue in assignment
03-error-in-fun.chpl:1169: error: illegal lvalue in assignment
03-error-in-fun.chpl:1170: error: illegal lvalue in assignment
03-error-in-fun.chpl:1171: error: illegal lvalue in assignment
03-error-in-fun.chpl:1172: error: illegal lvalue in assignment
03-error-in-fun.chpl:1173: error: illegal lvalue in assignment
03-error-in-fun.chpl:1174: error: illegal lvalue in assignment
03-error-in-fun.chpl:1175: error: illegal lvalue in assignment
03-error-in-fun.chpl:1176: error: illegal lvalue in assignment
03-error-in-fun.chpl:1177: error: illegal lvalue in assignment
03-error-in-fun.chpl:1178: error: illegal lvalue in assignment
03-error-in-fun.chpl:1179: error: illegal lvalue in assignment
03-error-in-fun.chpl:1180: error: illegal lvalue in assignment
03-error-in-fun.chpl:1181: error: illegal lvalue in assignment
03-error-in-fun.chpl:1182: error: illegal lvalue in assignment
03-error-in-fun.chpl:1183: error: illegal lvalue in assignment
03-error-in-fun.chpl:1184: error: illegal lvalue in assignment
03-error-in-fun.chpl:1185: error: illegal lvalue in assignment
03-error-in-fun.chpl:1186: error: illegal lvalue in assignment
03-error-in-fun.chpl:1187: error: illegal lvalue in assignment
03-error-in-fun.chpl:1188: error: illegal lvalue in assignment
03-error-in-fun.chpl:1189: error: illegal lvalue in assignment
03-error-in-fun.chpl:1190: error: illegal lvalue in assignment
03-error-in-fun.chpl:1191: error: illegal lvalue in assignment
03-error-in-fun.chpl:1192: error: illegal lvalue in assignment
03-error-in-fun.chpl:1201: error: illegal lvalue in assignment
03-error-in-fun.chpl:1202: error: illegal lvalue in assignment
03-error-in-fun.chpl:1203: error: illegal lvalue in assignment
03-error-in-fun.chpl:1204: error: illegal lvalue in assignment
03-error-in-fun.chpl:1205: error: illegal lvalue in assignment
03-error-in-fun.chpl:1206: error: illegal lvalue in assignment
03-error-in-fun.chpl:1207: error: illegal lvalue in assignment
03-error-in-fun.chpl:1208: error: illegal lvalue in assignment
03-error-in-fun.chpl:1209: error: illegal lvalue in assignment
03-error-in-fun.chpl:1210: error: illegal lvalue in assignment
03-error-in-fun.chpl:1211: error: illegal lvalue in assignment
03-error-in-fun.chpl:1212: error: illegal lvalue in assignment
03-error-in-fun.chpl:1213: error: illegal lvalue in assignment
03-error-in-fun.chpl:1214: error: illegal lvalue in assignment
03-error-in-fun.chpl:1215: error: illegal lvalue in assignment
03-error-in-fun.chpl:1216: error: illegal lvalue in assignment
03-error-in-fun.chpl:1217: error: illegal lvalue in assignment
03-error-in-fun.chpl:1218: error: illegal lvalue in assignment
03-error-in-fun.chpl:1219: error: illegal lvalue in assignment
03-error-in-fun.chpl:1220: error: illegal lvalue in assignment
03-error-in-fun.chpl:1221: error: illegal lvalue in assignment
03-error-in-fun.chpl:1222: error: illegal lvalue in assignment
03-error-in-fun.chpl:1223: error: illegal lvalue in assignment
03-error-in-fun.chpl:1224: error: illegal lvalue in assignment
03-error-in-fun.chpl:1225: error: illegal lvalue in assignment
03-error-in-fun.chpl:1234: error: illegal lvalue in assignment
03-error-in-fun.chpl:1235: error: illegal lvalue in assignment
03-error-in-fun.chpl:1236: error: illegal lvalue in assignment
03-error-in-fun.chpl:1237: error: illegal lvalue in assignment
03-error-in-fun.chpl:1238: error: illegal lvalue in assignment
03-error-in-fun.chpl:1239: error: illegal lvalue in assignment
03-error-in-fun.chpl:1240: error: illegal lvalue in assignment
03-error-in-fun.chpl:1241: error: illegal lvalue in assignment
03-error-in-fun.chpl:1242: error: illegal lvalue in assignment
03-error-in-fun.chpl:1243: error: illegal lvalue in assignment
03-error-in-fun.chpl:1244: error: illegal lvalue in assignment
03-error-in-fun.chpl:1245: error: illegal lvalue in assignment
03-error-in-fun.chpl:1246: error: illegal lvalue in assignment
03-error-in-fun.chpl:1247: error: illegal lvalue in assignment
03-error-in-fun.chpl:1248: error: illegal lvalue in assignment
03-error-in-fun.chpl:1249: error: illegal lvalue in assignment
03-error-in-fun.chpl:1250: error: illegal lvalue in assignment
03-error-in-fun.chpl:1251: error: illegal lvalue in assignment
03-error-in-fun.chpl:1252: error: illegal lvalue in assignment
03-error-in-fun.chpl:1253: error: illegal lvalue in assignment
03-error-in-fun.chpl:1254: error: illegal lvalue in assignment
03-error-in-fun.chpl:1255: error: illegal lvalue in assignment
03-error-in-fun.chpl:1256: error: illegal lvalue in assignment
03-error-in-fun.chpl:1257: error: illegal lvalue in assignment
03-error-in-fun.chpl:1258: error: illegal lvalue in assignment
03-error-in-fun.chpl:1306: In function 'funConstRef':
03-error-in-fun.chpl:1343: error: illegal lvalue in assignment
03-error-in-fun.chpl:1344: error: illegal lvalue in assignment
03-error-in-fun.chpl:1345: error: illegal lvalue in assignment
03-error-in-fun.chpl:1346: error: illegal lvalue in assignment
03-error-in-fun.chpl:1347: error: illegal lvalue in assignment
03-error-in-fun.chpl:1348: error: illegal lvalue in assignment
03-error-in-fun.chpl:1349: error: illegal lvalue in assignment
03-error-in-fun.chpl:1350: error: illegal lvalue in assignment
03-error-in-fun.chpl:1351: error: illegal lvalue in assignment
03-error-in-fun.chpl:1352: error: illegal lvalue in assignment
03-error-in-fun.chpl:1353: error: illegal lvalue in assignment
03-error-in-fun.chpl:1354: error: illegal lvalue in assignment
03-error-in-fun.chpl:1355: error: illegal lvalue in assignment
03-error-in-fun.chpl:1356: error: illegal lvalue in assignment
03-error-in-fun.chpl:1357: error: illegal lvalue in assignment
03-error-in-fun.chpl:1358: error: illegal lvalue in assignment
03-error-in-fun.chpl:1359: error: illegal lvalue in assignment
03-error-in-fun.chpl:1360: error: illegal lvalue in assignment
03-error-in-fun.chpl:1361: error: illegal lvalue in assignment
03-error-in-fun.chpl:1362: error: illegal lvalue in assignment
03-error-in-fun.chpl:1363: error: illegal lvalue in assignment
03-error-in-fun.chpl:1364: error: illegal lvalue in assignment
03-error-in-fun.chpl:1365: error: illegal lvalue in assignment
03-error-in-fun.chpl:1366: error: illegal lvalue in assignment
03-error-in-fun.chpl:1367: error: illegal lvalue in assignment
03-error-in-fun.chpl:1376: error: illegal lvalue in assignment
03-error-in-fun.chpl:1377: error: illegal lvalue in assignment
03-error-in-fun.chpl:1378: error: illegal lvalue in assignment
03-error-in-fun.chpl:1379: error: illegal lvalue in assignment
03-error-in-fun.chpl:1380: error: illegal lvalue in assignment
03-error-in-fun.chpl:1381: error: illegal lvalue in assignment
03-error-in-fun.chpl:1382: error: illegal lvalue in assignment
03-error-in-fun.chpl:1383: error: illegal lvalue in assignment
03-error-in-fun.chpl:1384: error: illegal lvalue in assignment
03-error-in-fun.chpl:1385: error: illegal lvalue in assignment
03-error-in-fun.chpl:1386: error: illegal lvalue in assignment
03-error-in-fun.chpl:1387: error: illegal lvalue in assignment
03-error-in-fun.chpl:1388: error: illegal lvalue in assignment
03-error-in-fun.chpl:1389: error: illegal lvalue in assignment
03-error-in-fun.chpl:1390: error: illegal lvalue in assignment
03-error-in-fun.chpl:1391: error: illegal lvalue in assignment
03-error-in-fun.chpl:1392: error: illegal lvalue in assignment
03-error-in-fun.chpl:1393: error: illegal lvalue in assignment
03-error-in-fun.chpl:1394: error: illegal lvalue in assignment
03-error-in-fun.chpl:1395: error: illegal lvalue in assignment
03-error-in-fun.chpl:1396: error: illegal lvalue in assignment
03-error-in-fun.chpl:1397: error: illegal lvalue in assignment
03-error-in-fun.chpl:1398: error: illegal lvalue in assignment
03-error-in-fun.chpl:1399: error: illegal lvalue in assignment
03-error-in-fun.chpl:1400: error: illegal lvalue in assignment
03-error-in-fun.chpl:1409: error: illegal lvalue in assignment
03-error-in-fun.chpl:1410: error: illegal lvalue in assignment
03-error-in-fun.chpl:1411: error: illegal lvalue in assignment
03-error-in-fun.chpl:1412: error: illegal lvalue in assignment
03-error-in-fun.chpl:1413: error: illegal lvalue in assignment
03-error-in-fun.chpl:1414: error: illegal lvalue in assignment
03-error-in-fun.chpl:1415: error: illegal lvalue in assignment
03-error-in-fun.chpl:1416: error: illegal lvalue in assignment
03-error-in-fun.chpl:1417: error: illegal lvalue in assignment
03-error-in-fun.chpl:1418: error: illegal lvalue in assignment
03-error-in-fun.chpl:1419: error: illegal lvalue in assignment
03-error-in-fun.chpl:1420: error: illegal lvalue in assignment
03-error-in-fun.chpl:1421: error: illegal lvalue in assignment
03-error-in-fun.chpl:1422: error: illegal lvalue in assignment
03-error-in-fun.chpl:1423: error: illegal lvalue in assignment
03-error-in-fun.chpl:1424: error: illegal lvalue in assignment
03-error-in-fun.chpl:1425: error: illegal lvalue in assignment
03-error-in-fun.chpl:1426: error: illegal lvalue in assignment
03-error-in-fun.chpl:1427: error: illegal lvalue in assignment
03-error-in-fun.chpl:1428: error: illegal lvalue in assignment
03-error-in-fun.chpl:1429: error: illegal lvalue in assignment
03-error-in-fun.chpl:1430: error: illegal lvalue in assignment
03-error-in-fun.chpl:1431: error: illegal lvalue in assignment
03-error-in-fun.chpl:1432: error: illegal lvalue in assignment
03-error-in-fun.chpl:1433: error: illegal lvalue in assignment
