name: actionlint

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Download actionlint
      id: get_actionlint
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      shell: bash
    - name: Check workflow files
      run: ${{ steps.get_actionlint.outputs.executable }} -color
      shell: bash
