name: build-CI-container

env:
  REGISTRY: ghcr.io
  # NOTE: IMAGE_NAME must be lowercase
  IMAGE_NAME: chapel-github-ci
  # NOTE: if this filename changes, also update in the on.paths section below
  DOCKERFILE: util/packaging/docker/github-ci/Dockerfile

# Serialize runs of this workflow on 'main', to prevent a build from an older
# ref pushing and overriding the results of a concurrently-building newer ref.
concurrency:
  group: ${{ github.workflow }}-${{ case(github.ref == 'refs/heads/main', 'main', github.sha) }}
  queue: max

on:
  push:
    branches: [ main ]
    # This limits the action so it only builds when this file changes
    paths:
      # unfortunately we can't use ${{env.DOCKERFILE}} here
      # see https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
      - util/packaging/docker/github-ci/Dockerfile
      # also trigger on changes to this workflow file itself
      - .github/workflows/build-CI-container.yml
  pull_request:
    paths:
      # same as for pushes above
      - util/packaging/docker/github-ci/Dockerfile
      - .github/workflows/build-CI-container.yml
  # Adds a "manual run" option in the GH UI
  workflow_dispatch:
  # Also rebuild weekly
  schedule:
    - cron: '0 0 * * 2'

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  build-ci-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ${{ env.DOCKERFILE }}
          # example: ghcr.io/chapel-lang/chapel-github-ci:latest
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
      - name: Push Docker Image if on main
        if: github.repository_owner == 'chapel-lang' && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'schedule'))
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
