name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true

# NOTE: each job has to specify the container section in its entirety, which is
# certainly repetetive, but the `defaults` section can't be applied and the `env`
# context isn't available in the `jobs` section
#   [1] https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts
#   [2] https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
# And other yml features like anchors and merge aren't supported
#   [3] https://github.com/actions/starter-workflows/issues/162

jobs:
  make_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: make check
      run: |
        ./util/buildRelease/smokeTest chpl

  make_doc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: make frontend-docs
      run: |
        make frontend-docs
    - name: make check-chpldoc && make docs
      # Uses a quickstart config to keep it from running too long
      # also builds chapel-py so those docs are included
      run: |
        ./util/buildRelease/smokeTest quickstart chapel-py docs
        tar -cvf docs.tar.gz -C doc/html .
    - name: upload docs
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: documentation
        path: docs.tar.gz

  make_mason:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: make mason
      # Use a quickstart config to keep it from running to long
      # While there, run a make check in that config for more coverage
      run: |
        ./util/buildRelease/smokeTest quickstart mason chpl

  check_dyno_linters:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: run dyno linters
      run: |
        CHPL_HOME=$PWD CHPL_HOST_COMPILER=clang make run-dyno-linters

  check_compiler_dyno_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: make test-dyno-with-asserts
      # 'make modules' so the ChapelSysCTypes module is available
      run: |
        CHPL_HOME=$PWD make modules
        CHPL_HOME=$PWD make DYNO_ENABLE_ASSERTIONS=1 test-dyno -j`util/buildRelease/chpl-make-cpu_count`
    - name: check undocumented symbols
      run: |
        CHPL_HOME=$PWD make DYNO_ENABLE_ASSERTIONS=1 chapel-py-venv -j`util/buildRelease/chpl-make-cpu_count`
        CHPL_HOME=$PWD $PWD/tools/chpldoc/findUndocumentedSymbols --ci --ignore-deprecated --ignore-unstable $PWD/modules/standard
    - name: lint standard modules
      run: |
        CHPL_HOME=$PWD make DYNO_ENABLE_ASSERTIONS=1 lint-standard-modules -j`util/buildRelease/chpl-make-cpu_count`
    - name: lint mason
      run: |
        CHPL_HOME=$PWD make DYNO_ENABLE_ASSERTIONS=1 lint-mason -j`util/buildRelease/chpl-make-cpu_count`

  make_check_llvm_none:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: set llvm_none make check
      run: |
       CHPL_LLVM=none ./util/buildRelease/smokeTest chpl

  check_annotations_rt_calls:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 100000
    - name: find bad runtime calls
      run: |
        ./util/devel/lookForBadRTCalls
    - name: find bad compiler calls
      run: |
        ./util/devel/lookForBadCompCalls
    - name: check annotations
      run: |
        CHPL_LLVM=none make test-venv
        CHPL_LLVM=none CHPL_HOME=$PWD ./util/test/run-in-test-venv.bash ./util/test/check_annotations.py
    - name: check perf graphs
      run: |
        python3 ./util/test/check_perf_graphs.py
    - name: smokeTest lint
      run: |
        ./util/buildRelease/smokeTest lint

  check_large_files:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      IGNORE_LABEL: "large files ok"
    steps:
      - name: count PR commits
        run: echo "PR_NUM_COMMITS=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> "${GITHUB_ENV}"
      - name: checkout commits on PR branch
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: ${{ env.PR_NUM_COMMITS }}
      - name: check commits for large files
        run: |
          FILE_SIZE_LIMIT_KB=1024

          baseSHA=${{github.event.pull_request.base.sha}}
          headSHA=${{github.event.pull_request.head.sha}}

          echo "Base SHA: $baseSHA"
          echo "Head SHA: $headSHA"
          echo "${{github.event.pull_request.commits}} commits in PR"

          # Loop backward through commits added in the PR, starting from the
          # latest.
          commitIdx=0
          errorCount=0
          for commit in $(git rev-list $baseSHA..$headSHA)
          do
            echo "Checking commit: $commit"
            git checkout -q $commit

            # Get list of added, copied, or modified files from this commit.
            newFiles=$(git diff --name-only --diff-filter=ACM $commit^ $commit)
            while read -r file; do
              if [ "$file" = "" ]; then
                  continue
              fi
              echo "Checking file: $file"

              file_size=$(ls -l "$file" | awk '{print $5}')
              file_size_kb=$((file_size / 1024))

              if [ "$file_size_kb" -ge "$FILE_SIZE_LIMIT_KB" ]; then
                echo "Error: ${file} is too large (size ${file_size_kb}KB, limit ${FILE_SIZE_LIMIT_KB}KB). Introduced in commit: $commit"
                errorCount=$((errorCount+1))
              fi
            done <<< "$newFiles"

            # Stop after going through the number of commits this PR has.
            commitIdx=$((commitIdx+1))
            if [ "$commitIdx" =  "${{github.event.pull_request.commits}}" ]; then
              echo "Stopping after $commitIdx commits, on commit $commit"
              break
            fi
          done

          if [ "$errorCount" -gt 0 ]; then
            if [ ${{ contains(github.event.*.labels.*.name, env.IGNORE_LABEL) }} = "true" ]; then
              echo "Ignoring errors due to '${{ env.IGNORE_LABEL }}' label presence"
            else
              echo "If you want to ignore errors for this PR, add the label '${{ env.IGNORE_LABEL }}', then close and reopen the PR"
              exit 1
            fi
          fi

  publish-docs:
    if: github.event_name == 'push' && github.repository == 'chapel-lang/chapel'
    runs-on: ubuntu-latest
    needs: make_doc
    steps:
      - name: download docs
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: documentation

      - name: setup keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.WEBSITE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.WEBSITE_KNOWN_HOSTS}}" > ~/.ssh/known_hosts

      - name: push docs (retrying)
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_seconds: 60
          retry_wait_seconds: 30
          command: |
            echo "extract docs"
            tar -xvf docs.tar.gz
            echo "Publish module docs to web server"
            # py-modindex.html is not needed
            rm -f py-modindex.html
            # Remove all hidden files except .htaccess
            find . -maxdepth 1 -type f -name ".*" ! -name ".htaccess" -exec rm -f {} +
            rsync -avz --cvs-exclude --delete --relative . ${{ secrets.WEBSITE_USER }}@${{ secrets.WEBSITE_URL }}:${{ secrets.WEBSITE_PATH }}
            rm ~/.ssh/id_rsa
            rm ~/.ssh/known_hosts

  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          severity: error
          ignore_paths: ./test/* ./third-party/*

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # 26.5.1
        with:
          options: "--check --verbose --line-length 80 --extend-exclude '^/(third-party|test)/'"
          src: "."
      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e # 26.5.1
        with:
          options: "--check --verbose --line-length 80 --extend-exclude '(install|build)/'"
          src: "third-party/chpl-venv"

  test_chpl_language_server:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      id: changes
      with:
        filters: |
          cls_sources:
            - 'tools/chapel-py/**'
            - 'tools/chpl-language-server/**'
    - name: test chpl-language-server
      if: steps.changes.outputs.cls_sources == 'true'
      run: |
        make test-chpl-language-server -j`util/buildRelease/chpl-make-cpu_count`

  release-tarball-smoke-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: create release tarball
      run: |
        export CHPL_TEST_RELEASE_NORECURSE=1
        ./util/cron/test-release.bash
    - name: upload release tarball as artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: ./tar/chapel-test.tar.gz
        archive: false

  chapel-code-smoke-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        config: [gasnet, none]
        exclude:
          - os: macos-latest
            config: gasnet
    runs-on: ${{ matrix.os }}
    steps:
      - name: print config info
        run: |
          echo "${{ matrix.os }}"
          echo "${{ matrix.config }}"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: install deps
        run: |
          if [[ "${{ matrix.os }}" == "macos"* ]] ; then
            brew install llvm
          else
            sudo apt install \
              clang \
              libclang-dev \
              libclang-cpp-dev \
              libedit-dev \
              llvm \
              llvm-dev
          fi
      - name: setup env and run ./util/buildRelease/smokeTest
        run: |
          set -ex

          source ./util/cron/common.bash

          if [[ "${{ matrix.os }}" == "macos"* ]] ; then
            source ./util/cron/common-darwin.bash
          fi

          if [[ "${{ matrix.config }}" == "gasnet" ]] ; then
            source ./util/cron/common-gasnet.bash
            # Silence warnings about not using ibv despite ibv hardware presence
            export GASNET_QUIET=yes
          fi

          export NIGHTLY_TEST_SETTINGS=true
          export CHPL_SMOKE_SKIP_MAKE_MASON=true

          ./util/buildRelease/smokeTest

  test-homebrew:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: print config info
        run: |
          echo "${{ matrix.os }}"
          echo "${{ matrix.config }}"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: run homebrew testing
        run: |
          if [[ "${{ matrix.os }}" == "macos"* ]] ; then
            ./util/cron/test-homebrew.bash
          else
            ./util/cron/test-homebrew-linux.bash
          fi

  test-networking-packages:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: run test-networking-packages.bash
      run: |
        ./util/cron/test-networking-packages.bash

  # This job exists to have a single check for which failure means merging
  # should be blocked, for GH required status checks purposes.
  # It runs (and fails) if any of the jobs listed in its `needs` ran and
  # failed; otherwise, it will be skipped, which GH considers acceptable for a
  # 'required' check.
  # When adding a new job which we would like to block PR merging, add it to
  # the `needs` list below. Note that if a dependent job is _skipped_, it will
  # not trigger failure of this job.
  checks-alert-failure:
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    needs:
      - make_check
      - make_doc
      - make_mason
      - check_dyno_linters
      - check_compiler_dyno_tests
      - make_check_llvm_none
      - check_annotations_rt_calls
      - check_large_files
      - publish-docs
      - run-shellcheck
      - check-format
      - test_chpl_language_server
      - release-tarball-smoke-test
      - chapel-code-smoke-test
      - test-homebrew
      - test-networking-packages
    steps:
      - name: Fail
        run: |
          echo "A required status check has failed"
          exit 1
