# Critical, fastest-running CI checks for a short feedback loop (per-commit).
name: Core CI Checks

on:
  workflow_call:
    secrets:
      WEBSITE_KEY:
        required: false
      WEBSITE_KNOWN_HOSTS:
        required: false
      WEBSITE_USER:
        required: false
      WEBSITE_URL:
        required: false
      WEBSITE_PATH:
        required: false

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true
  APT_INSTALL_TIMEOUT_MINS: 5

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  test-homebrew:
    strategy:
      fail-fast: false
      matrix:
        os: [xcode-27]
    runs-on: ${{ matrix.os }}
    steps:
      - name: save matrix properties to env
        run: |
          echo "OS=${{ matrix.os }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: run homebrew testing
        run: |
          # if [[ "$OS" == "macos"* ]] ; then
            ./util/cron/test-homebrew.bash
          # else
            # ./util/cron/test-homebrew-linux.bash
          # fi
      - name: upload homebrew log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: homebrew-log
          path: /Users/runner/Library/Logs/Homebrew/chapel/*

