# Dummy DCO workflow which gives a passing status in the merge queue, to work
# around https://github.com/dcoapp/app/issues/199 and
# https://github.com/dcoapp/app/issues/302 .

name: DCO

on:
  merge_group:

permissions:
  contents: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  DCO:
    runs-on: ubuntu-slim
    steps:
      - name: pass (dummy workflow to satisfy merge queue requirement)
        run: exit 0
