# Reusable workflow to build a Chapel Docker image.
name: Build Docker image

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
      secrets:
        DOCKERHUB_USER:
          required: true
        DOCKERHUB_PAT:
          required: true

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  build-test-image-each-arch:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      # packages: write # To push images to ghcr
    env:
      CONFIG: ${{ inputs.config }}
      ARCH: ${{ endsWith(matrix.runner, '-arm') && 'arm64' || 'x86' }}
      REGISTRY: "docker.io"
      NAMESPACE: "chapel"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: set up build env and vars
        run: |
          MAKE_THREADS=$(util/buildRelease/chpl-make-cpu_count)

          TAG="$GITHUB_SHA"
          name_prefix="chapel"
          BASE_IMAGE_FULL_NAME="$REGISTRY/$NAMESPACE/$name_prefix:$TAG"
          IMAGE_TARBALL="chapel-image-$image_name-$TAG-$ARCH.tar"

          if [[ "$CONFIG" == "base" ]]; then
            image_name="$name_prefix"
            DOCKERFILE="./Dockerfile"
            TEST_SCRIPT="util/cron/docker-chapel.bash"
          else
            image_name="$name_prefix-$CONFIG"
            DOCKERFILE="util/packaging/docker/$CONFIG/Dockerfile"
            TEST_SCRIPT="util/cron/docker-gasnet.bash"

            patch "$DOCKERFILE" << EOF
          1c1
          < FROM chapel/chapel:latest
          ---
          > FROM $BASE_IMAGE_FULL_NAME
          EOF
          fi

          IMAGE_FULL_NAME="$REGISTRY/$NAMESPACE/$image_name:$TAG"

          {
            echo "BASE_IMAGE_FULL_NAME=$BASE_IMAGE_FULL_NAME"
            echo "IMAGE_TARBALL=$IMAGE_TARBALL"
            echo "MAKE_THREADS=$MAKE_THREADS"
            echo "TAG=$TAG"
            echo "DOCKERFILE=$DOCKERFILE"
            echo "TEST_SCRIPT=$TEST_SCRIPT"
            echo "IMAGE_FULL_NAME=$IMAGE_FULL_NAME"
          } >> "$GITHUB_ENV"
      - name: build image ${{ env.IMAGE_FULL_NAME }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ${{ env.DOCKERFILE }}
          build-args: "MAKE_THREADS=${{ env.MAKE_THREADS }}"
          tags: ${{ env.IMAGE_FULL_NAME }}
          load: true
      - name: test image
        run: |
          cp test/release/examples/hello.chpl .
          docker run --rm -i "$IMAGE_FULL_NAME" < "$TEST_SCRIPT"
      - name: export image to tarball
        run: |
          docker image save -o "$IMAGE_TARBALL" "$BASE_IMAGE_FULL_NAME"
      - name: upload image tarball
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.IMAGE_TARBALL }}
          path: ${{ env.IMAGE_TARBALL }}
      # TODO: push to ghcr / dockerhub
