name: email
on:
  # This workflow is intended to run when a PR is merged into main.
  # Although it is per-PR, triggering on pull_request would not provide access
  # to the required secret for sending emails, and pull_request_target is
  # dangerous. Instead, trigger on the push to main, and find the
  # corresponding PR to gather info from.
  push:
    branches: [ main ]
  # TODO: remove PR trigger which was just for testing
  pull_request:

# Serialize runs of this workflow to ensure emails are sent in the same order
# as merges are done.
concurrency:
  group: ${{ github.workflow }}
  queue: max

permissions:
  contents: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  send_email:
    if: github.repository == 'chapel-lang/chapel'
    runs-on: ubuntu-slim
    env:
      EMAIL_BODY_FILENAME: email.md
      GH_TOKEN: ${{ github.token }}
      PR_JSON: pr.json
      DIFF_MAX_LINES: 1000
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: .
      - name: generate fallback email body
        run: |
          cat << EOF > "$EMAIL_BODY_FILENAME"
          Failure encountered generating PR merge email for commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).

          Run ID: [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          EOF
      - name: find PR associated with this push and grab info
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_seconds: 60
          retry_wait_seconds: 30
          command: |
            set -exuo pipefail

            pr_number=$(gh pr list --search "25b5b2d9a76ecdae3e68d8188b103ddbd657e8f2" --state merged --json "number" | jq '.[0].number')
            if [ -z "$pr_number" ]; then
              echo "Couldn't find PR corresponding to commit 25b5b2d9a76ecdae3e68d8188b103ddbd657e8f2" | tee -a "$EMAIL_BODY_FILENAME"
              exit 1
            fi

            gh api "/repos/${{ github.repository }}/pulls/$pr_number" | jq '.' | tee $PR_JSON
      - name: generate email body from PR info
        run: |
          diff=$(git --no-pager diff --merge-base --name-status --diff-filter=ACDMRT ${{github.event.pull_request.base.sha}} ${{github.event.pull_request.head.sha}})
          # Cut off long diff output after some number of lines
          diff=$(echo "$diff" | awk "NR <= $DIFF_MAX_LINES; NR > $DIFF_MAX_LINES { print \"(diff output truncated at $DIFF_MAX_LINES lines)\"; exit }")

          cat << EOF > "$EMAIL_BODY_FILENAME"
          Branch: $(jq '.head.ref' $PR_JSON)
          Revision: $GITHUB_SHA
          Author: $(jq '.merged_by.login' $PR_JSON)
          Link: $(jq '.html_url' $PR_JSON)
          Log Message:
          $(jq '.title' $PR_JSON)

          $(jq '.body' $PR_JSON)

          Compare: $(jq '.html_url' $PR_JSON)/changes

          Diff:
                   $diff
                   $(jq '.diff_url' $PR_JSON)
          EOF
      - name: Send mail
        if: ${{ ! always() }}
        uses: dawidd6/action-send-mail@67ce3558d613188179559c61d3565140cf389968 # v22
        with:
           # Required mail server address if not connection_url:
           server_address: ${{ secrets.SMTP_PROVIDER}}
           server_port: 465
           # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
           # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}}
           # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
           # Required mail subject:
           subject: "[Chapel Merge] ${{github.event.pull_request.title}}"
           # Required recipients' addresses:
           to: chapel+commits@discoursemail.com
           # Required sender (supported formats: see "Supported address formats" below)
           from:  "${{env.AUTHOR}} <chapel_commits@cray.com>"
           body: file://${{ env.EMAIL_BODY_FILENAME }}
