name: email
on:
    # this workflow is intended to run on merges from a forked repo to main(base-repo). Use pull_request_target
    # this will provide read access to the secrets in main
    push:
    pull_request:
    #pull_request_target:
      #types:
       # - closed
      
jobs: 
  send_email:
   # run this workflow step only when the PR is merged 
    # if:  github.event.pull_request.merged == true 
    runs-on: ubuntu-latest 
    steps:
      - name: print git events
        run:  cat "$GITHUB_EVENT_PATH"                     
      - name: print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
      - name: get commits payload
        env:
          COMMIT_URL: ${{github.event.pull_request._links.commits.href}}
        run: |
              curl --location --request GET 'https://api.github.com/repos/chapel-lang/chapel/pulls/21013/commits' --header 'X-API-Key: ${{ secrets.GITHUB_TOKEN}}' -o commits.json
              echo "AUTHOR=$(jq -r '.[0].commit.author.name' commits.json)" >> $GITHUB_ENV   
              echo "LINK=$(jq -r '.[0].html_url' commits.json)" >> $GITHUB_ENV
              echo "MESSAGE=$((jq  '.[0].commit.message' commits.json)| awk -F'\\\\n' '{print $1}' | sed 's/\"//g')" >> $GITHUB_ENV 
              echo "${{github.event.repository.html_url}}" >> blah.txt
              cat blah.txt
              echo "COMPARE_URL= $( echo '${{github.event.repository.html_url}}/compare/${{github.event.pull_request.base.sha}}...${{ github.event.pull_request.merge_commit_sha}}' )" >> $GITHUB_ENV     
              echo "LOG= $(echo 'Resolves #21073\r\n\r\nThis fixes a bug where an actual argument was always considered a \"use\" upon a call to a virtually-dispatched method even when the corresponding formal had a ref or [in]out intent.\r\n\r\nThe bug was observed when such an actual argument was an array indexing expression, which involved return intent overloading. Because of the bug, the return-value overload was chosen instead of the return-ref one.\r\n\r\nNext steps: check if this bug can occur upon calls to ftable-ed functions.\r\n\r\nTesting: standard paratest; gasnet paratest over multilocale tests.' | sed  's/\\r\\n\\r\\n/<p>/g' |  sed  's/\\r\\n/<br>/g')" >> $GITHUB_ENV
              echo "FILES_CHANGED=$(echo '${{github.event.pull_request._links.html.href}}/files' )" >> $GITHUB_ENV
              
      - name: checkout
        uses: actions/checkout@v3
        # To get git diff on the files that were changed in the PR checkout with fetch-depth 2.
        with:
          fetch-depth: 0           
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          separator: ","    
      - name: Parse changed files
        id: parsed-output
        run: |
              echo "OUTPUT= $(echo ${{steps.changed-files.outputs.modified_files}} |  sed 's/\,/\\n/g' )" >> $GITHUB_ENV    
                
      - name: Send mail  
        uses: dawidd6/action-send-mail@v3
        with:
           # Required mail server address if not connection_url:
           server_address: ${{ secrets.SMTP_PROVIDER}}
           server_port: 465
           # Optional whether this connection use TLS (default is true if server_port is 465)
           secure: true
           # Optional (recommended): mail server username:
           username:  ${{ secrets.MAIL_USERNAME}} 
           # Optional (recommended) mail server password:
           password: ${{secrets.MAIL_PASSWORD}}
           # Required mail subject:
           subject: "Plain Body Test [CHAPEL MERGE] Hide stderr for Mason's `runCommand` "
           # Required recipients' addresses:
           # to: chapel+commits@discoursemail.com
           to: bhavani@hpe.com
           # Required sender full name (address can be skipped):
           from:  ${{env.AUTHOR}}
        
           body: |
                     Branch :  ${{github.ref}} 
                     Revision ${{ github.event.pull_request.merge_commit_sha }}  
                     Author  ${{ env.AUTHOR}} 
                     Link  ${{github.event.pull_request._links.html.href}}         
                     Log Message  
                           ${{env.LOG}} 
                          
                     ${{env.OUTPUT}} 
                     ${{ github.event.push.head_commit.message }}
                     "Resolves #21073\r\n\r\nThis fixes a bug where an actual argument was always considered a \"use\" upon a call to a virtually-dispatched method even when the corresponding formal had a ref or [in]out intent.\r\n\r\nThe bug was observed when such an actual argument was an array indexing expression, which involved return intent overloading. Because of the bug, the return-value overload was chosen instead of the return-ref one.\r\n\r\nNext steps: check if this bug can occur upon calls to ftable-ed functions.\n\nTesting: standard paratest; gasnet paratest over multilocale tests."

              
           # Optional converting Markdown to HTML (set content_type to text/html too):
           #convert_markdown: true
           # Optional priority: 'high', 'normal' (default) or 'low'
           priority: low
