name: Extended CI checks

on:
  workflow_call:

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  arkouda-smoke-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      ARROW_VERSION: "19.0.1"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: checkout Arkouda
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: Bears-R-Us/arkouda
        path: arkouda
        persist-credentials: false
    - name: apt install some Arkouda deps
      run: |
        apt update && apt install -y \
          libzmq3-dev \
          libcurl4-openssl-dev
    - name: set Arkouda env vars
      run: |
        cd arkouda
        {
          echo "ARKOUDA_URL=$(pwd)"
          echo "ARKOUDA_DEP_DIR=$(pwd)/dep"
          echo "ARKOUDA_SKIP_CHECK_DEPS=true"
          echo "ARKOUDA_SHA=$(git rev-parse HEAD)"
        } >> "$GITHUB_ENV"
    - name: cache Arkouda deps install
      id: cache-arkouda-deps
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      with:
        path: ${{ env.ARKOUDA_DEP_DIR }}
        key: arkouda-${{ env.ARKOUDA_SHA }}
    - name: install Arkouda deps
      if: steps.cache-arkouda-deps.outputs.cache-hit != 'true'
      run: |
        num_procs=$(util/buildRelease/chpl-make-cpu_count)
        cd arkouda
        # Download sources serially first before building, as it is flaky and
        # that'll make it easier to diagnose failures.
        make deps-download-source
        make -j"$num_procs" install-deps
    - name: check contents of Arkouda deps install
      run: |
        test -d "$ARKOUDA_DEP_DIR"
        ls -R "$ARKOUDA_DEP_DIR"
    - name: build Chapel and run Arkouda smoke testing
      run: |
        source ./util/cron/common.bash
        source ./util/setchplenv.bash
        export CHPL_TEST_ARKOUDA_PERF=false
        source ./util/cron/common-arkouda.bash

        export NIGHTLY_TEST_SETTINGS=true
        export CHPL_SMOKE_SKIP_DOC=true
        export CHPL_SMOKE_SKIP_MAKE_MASON=true
        export ARKOUDA_SMOKE_TEST=true
        ./util/buildRelease/smokeTest
        make -j"$(util/buildRelease/chpl-make-cpu_count)" test-venv

        start_test test/studies/arkouda/

  define-linux-package-configs:
    runs-on: ubuntu-slim
    outputs:
      distro_configs: ${{ steps.configs.outputs.distro_configs }}
    env:
      PACKAGING_DIR: "util/packaging"
    steps:
      - name: sparse check out ${{ env.PACKAGING_DIR }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: ${{ env.PACKAGING_DIR }}
      - name: get list of distros to build for
        id: configs
        run: |
          cd $PACKAGING_DIR

          distro_configs=""

          pushd apt
          distro_configs="$(find . -type d -not ( -name test -o -name common ) -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}') $distro_configs"
          popd

          pushd rpm
          distro_configs="$(find . -type d -not ( -name test -o -name common ) -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}') $distro_configs"
          popd

          echo "distro_configs=[$distro_configs]" >> "$GITHUB_OUTPUT"

  build-packaging-tarball:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: build tarball
        run: |
            export CHPL_VERSION='release'
            export CHPL_GEN_RELEASE_SKIP_DOCS=true
            ./util/cron/create_tarball.bash
      - name: upload tarball as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./tar/chapel.tar.gz
          archive: false
          name: packaging-tarball

  build-linux-packages:
    needs: [define-linux-package-configs, build-packaging-tarball]
    strategy:
      fail-fast: false
      matrix:
        distro: ${{ fromJSON(needs.define-linux-packages-configs.outputs.apptainer_configs) }}
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    env:
      DISTRO: ${{ matrix.distro }}
      ARCH: ${{ endsWith(matrix.runner, '-arm') && 'arm64' || 'x86' }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: download packaging tarball
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: packaging-tarball
      - name: sparse check out util/
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: util/
      - name: build package ${{ env.DISTRO }} for ${{ env.ARCH }}
        run: |
          OS=$DISTRO
          PACKAGE_NAME=chapel
          PARALLEL=$(util/buildRelease/chpl-make-cpu_count)

          echo "Building the Chapel Package for: "
          echo "Chapel Version = $CHPL_VERSION"
          echo "Package Version = $PACKAGE_VERSION"
          echo "OS = $DISTRO"
          echo "PACKAGE = $PACKAGE_NAME"
          echo "PACKAGE_TYPE = $PACKAGE_TYPE"
          echo "CHPL_TARBALL_LOCATION = $CHPL_TARBALL_LOCATION"

          ./util/cron/create_release_aptrpm.bash
      - name: archive package as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: util/packaging/**/*.{deb,rpm}
          archive: false

  check_blog:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: build chapel
      run: |
        ./util/buildRelease/smokeTest chpl mason
    - name: build test-venv
      run: |
        make test-venv
    - name: clone blog
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        repository: chapel-lang/chapel-blog
        path: chapel-blog
    - name: check blog
      run: |
        . ./util/setchplenv.sh
        PARALLEL=$(util/buildRelease/chpl-make-cpu_count)
        start_test --parallel "$PARALLEL" --parallel-sub_test "$PARALLEL" --allow-unsafe-parallel chapel-blog/content/ chapel-blog/chpl-src

  define-portability-test-configs:
    runs-on: ubuntu-slim
    outputs:
      apptainer_configs: ${{ steps.configs.outputs.apptainer_configs }}
      vagrant_configs: ${{ steps.configs.outputs.vagrant_configs }}
    env:
      PORTABILITY_TEST_DIR: "util/devel/test/portability"
    steps:
      - name: sparse check out ${{ env.PORTABILITY_TEST_DIR }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: ${{ env.PORTABILITY_TEST_DIR }}
      - name: get list of current Apptainer and Vagrant configs
        id: configs
        run: |
          cd ${{ env.PORTABILITY_TEST_DIR }}

          pushd apptainer/current
          apptainer_configs=$(find . -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}')
          echo "apptainer_configs=[$apptainer_configs]" >> "$GITHUB_OUTPUT"
          popd

          pushd vagrant/current
          vagrant_configs=$(find . -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}')
          echo "vagrant_configs=[$vagrant_configs]" >> "$GITHUB_OUTPUT"
          popd

  portability-tests-apptainer:
    runs-on: ubuntu-latest
    needs: define-portability-test-configs
    strategy:
      fail-fast: false
      matrix:
        apptainer_config: ${{ fromJSON(needs.define-portability-test-configs.outputs.apptainer_configs) }}
    env:
      apptainer_config: ${{ matrix.apptainer_config }}
    steps:
      - name: install Apptainer
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt update
          sudo apt install -y apptainer
      - name: print Apptainer version
        run: |
          apptainer --version
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: set vars to work from correct branch
        run: |
          {
            echo "GIT_REPO_URL=$PWD"
            echo "GIT_COMMIT=${{ github.sha }}"
          } >> "$GITHUB_ENV"
      - name: test Apptainer config ${{ env.APPTAINER_IMAGE }}
        run: |
          export APPTAINER_IMAGE=$apptainer_config
          MAKEJ="-j$(./util/buildRelease/chpl-make-cpu_count)"
          export MAKEJ

          cd ./util/devel/test/portability/apptainer

          ./chapel-quickstart-fresh.sh
          # Default config requires LLVM
          if [[ "$APPTAINER_IMAGE" != *"nollvm" ]]; then
              ./chapel-default-fresh.sh
          fi

  gcc-version-tests:
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [9, 10, 11, 12, 13, 14, 15, 16]
    runs-on: ubuntu-latest
    steps:
      - name: save matrix properties to env
        run: |
          echo "GCC_VERSION=${{ matrix.gcc_version }}" >> "$GITHUB_ENV"
      - name: Install GCC
        uses: egor-tensin/setup-gcc@a2861a8b8538f49cf2850980acccf6b05a1b2ae4 # v2
        with:
          version: ${{ matrix.gcc_version }}
      - name: Check desired GCC version is default
        run: |
          actual_gcc_version=$(gcc -dumpversion)
          gcc_major_version=$(cut -d. -f1 <<< "$actual_gcc_version")
          if [ "$gcc_major_version" != "$GCC_VERSION" ]; then
            echo "Wrong gcc version"
            echo "Expected Version: $GCC_VERSION Actual Version: $gcc_major_version"
            exit 2
          fi
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Compile Chapel and run example tests
        run: |
          source util/setchplenv.bash

          # Use CHPL_LLVM=none to avoid using a system LLVM potentially linked
          # with a different and incompatible version of GCC
          export CHPL_LLVM=none
          export CHPL_LLVM_SUPPORT=bundled
          unset CHPL_LLVM_CONFIG

          # Set environment variables to nudge cmake towards desired GCC
          export CHPL_CMAKE_USE_CC_CXX=1
          CC=$(which gcc)
          export CC
          CXX=$(which g++)
          export CXX

          export CHPL_LAUNCHER=none

          num_procs=$(./util/buildRelease/chpl-make-cpu_count)
          make -j"$num_procs"
          make -j"$num_procs" test-venv
          make -j"$num_procs" spectests

          start_test --parallel "$num_procs" test/release/examples

  python-version-tests:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Check desired Python version is default
        run: |
          source util/cron/common-python.bash
          check_python_version "${{ matrix.python_version }}"
      - name: Install LLVM dependency
        run: |
          sudo apt install \
            clang \
            libclang-dev \
            libclang-cpp-dev \
            libedit-dev \
            llvm \
            llvm-dev
      - name: Compile Chapel and run example tests
        run: |
          source util/setchplenv.bash

          export CHPL_LAUNCHER=none

          num_procs=$(./util/buildRelease/chpl-make-cpu_count)
          make -j"$num_procs"
          make -j"$num_procs" test-venv
          make -j"$num_procs" spectests

          start_test --parallel "$num_procs" test/release/examples test/library/packages/Python test/interop/python

  llvm-version-tests:
    strategy:
      fail-fast: false
      matrix:
        llvm_version: [15, 16, 17, 18, 19, 20, 21, 22]
    runs-on: ${{ matrix.llvm_version >= 17 && 'ubuntu-latest' || 'ubuntu-22.04' }}
    steps:
      - name: Install LLVM ${{ matrix.llvm_version }} from official convenience script
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh

          # Work around https://github.com/llvm/llvm-project/issues/62152
          set_var=${{ matrix.llvm_version == 15 && 'DPKG_FORCE=overwrite' || '' }}

          sudo $set_var ./llvm.sh "${{ matrix.llvm_version }}" all

          echo "CHPL_LLVM_CONFIG=$(which llvm-config-${{ matrix.llvm_version }})" >> "$GITHUB_ENV"
      - name: Check desired LLVM version is default
        run: |
          set -exuo pipefail

          # Check LLVM version via llvm-config from CHPL_LLVM_CONFIG
          llvm_version=$($CHPL_LLVM_CONFIG --version)
          llvm_version_major=$(cut -d. -f1 <<< "$llvm_version")
          if [ "$llvm_version_major" != "${{ matrix.llvm_version }}" ]; then
            echo "Wrong LLVM version"
            echo "Expected Version: ${{ matrix.llvm_version }} Actual Version: $llvm_version"
            exit 2
          fi
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Compile Chapel and run example tests
        run: |
          source util/setchplenv.bash

          export CHPL_LLVM=system

          export CHPL_LAUNCHER=none

          num_procs=$(./util/buildRelease/chpl-make-cpu_count)
          make -j"$num_procs"
          make -j"$num_procs" test-venv
          make -j"$num_procs" spectests

          start_test --parallel "$num_procs" test/release/examples test/llvm

  release-tarball-smoke-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: set vars to make tarball from correct branch
      run: |
        {
          echo "CHPL_HOME_REPOSITORY=$PWD"
          echo "CHPL_GEN_RELEASE_COMMIT=${{ github.sha }}"
        } >> "$GITHUB_ENV"
    - name: create release tarball
      run: |
        export CHPL_TEST_RELEASE_NORECURSE=1
        ./util/cron/test-release.bash
    - name: upload release tarball as artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: ./tar/chapel-test.tar.gz
        archive: false

  test-homebrew:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: save matrix properties to env
        run: |
          echo "OS=${{ matrix.os }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: run homebrew testing
        run: |
          if [[ "$OS" == "macos"* ]] ; then
            ./util/cron/test-homebrew.bash
          else
            ./util/cron/test-homebrew-linux.bash
          fi

  test-c2chapel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: run test-c2chapel.bash
      run: |
        ./util/cron/test-c2chapel.bash
