# Longest-running CI checks which should run less frequently, and need not be
# pre-merge. These are required for our full test coverage of Chapel.
name: Full CI checks

on:
  workflow_call:

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true
  APT_INSTALL_TIMEOUT_MINS: 5

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  arkouda-main-smoke-test:
    uses: $/.github/workflows/arkouda-smoke-test.yml
    with:
      arkouda-version: "main"

  test-make-install-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: run test-make-install-check.bash
      run: |
        ./util/cron/test-make-install-check.bash

  build-linux-packages:
    uses: $/.github/workflows/package-builds.yml

  paratest-linux64-c-backend:
    name: Chapel paratest on linux64 with C backend
    uses: $/.github/workflows/ga-paratest.yml
    permissions:
      contents: read
      packages: read
      actions: write
    with:
      configuration: linux64-c-backend
      cron-script: util/cron/test-c-backend.bash
      build-steps: |
        num_procs=$(util/buildRelease/chpl-make-cpu_count)
        make -j"$num_procs" DEBUG=0 WARNINGS=1 OPTIMIZE=1 \
          all test-venv mason
  paratest-darwin:
    name: Chapel paratest on darwin
    uses: $/.github/workflows/ga-paratest.yml
    permissions:
      contents: read
      packages: read
      actions: write
    with:
      configuration: darwin
      runner: macos-latest
      use-container: false
      cron-script: util/cron/test-darwin.bash
      pre-build-steps: |
        brew install llvm@22
