# Longest-running CI checks which should run less frequently, and need not be
# pre-merge. These are required for our full test coverage of Chapel.
name: Full CI checks

on:
  workflow_call:

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  trigger-failure:
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
  also-trigger-failure:
    runs-on: ubuntu-slim
    steps:
      - name: break it
        run: exit 1

  define-portability-test-configs:
    runs-on: ubuntu-slim
    outputs:
      apptainer_configs: ${{ steps.configs.outputs.apptainer_configs }}
      vagrant_configs: ${{ steps.configs.outputs.vagrant_configs }}
    env:
      PORTABILITY_TEST_DIR: "util/devel/test/portability"
    steps:
      - name: sparse check out ${{ env.PORTABILITY_TEST_DIR }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: ${{ env.PORTABILITY_TEST_DIR }}
      - name: get list of current Apptainer and Vagrant configs
        id: configs
        run: |
          cd ${{ env.PORTABILITY_TEST_DIR }}

          pushd apptainer/current
          apptainer_configs=$(find . -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}')
          echo "apptainer_configs=[$apptainer_configs]" >> "$GITHUB_OUTPUT"
          popd

          pushd vagrant/current
          vagrant_configs=$(find . -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | awk '{ printf "%s%s", sep, "\""$0"\"", sep=", "}')
          echo "vagrant_configs=[$vagrant_configs]" >> "$GITHUB_OUTPUT"
          popd

  portability-tests-apptainer:
    runs-on: ubuntu-latest
    needs: define-portability-test-configs
    strategy:
      fail-fast: false
      matrix:
        apptainer_config: ${{ fromJSON(needs.define-portability-test-configs.outputs.apptainer_configs) }}
    env:
      APPTAINER_IMAGE: ${{ matrix.apptainer_config }}
      apptainer_dir: ./util/devel/test/portability/apptainer
    steps:
      - name: install Apptainer
        run: |
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt update
          sudo apt install -y apptainer
      - name: print Apptainer version
        run: |
          apptainer --version
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: set vars to work from correct branch
        run: |
          {
            echo "GIT_REPO_URL=$PWD"
            echo "GIT_COMMIT=${{ github.sha }}"
          } >> "$GITHUB_ENV"
      - name: build Apptainer image for config ${{ env.APPTAINER_IMAGE }} (retrying)
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          max_attempts: 3
          timeout_minutes: 30
          retry_wait_seconds: 60
          command: |
            export APPTAINER_IMAGE
            cd "$apptainer_dir"
            ./image-rebuild.sh
      - name: test Apptainer config ${{ env.APPTAINER_IMAGE }}
        run: |
          MAKEJ="-j$(./util/buildRelease/chpl-make-cpu_count)"
          export MAKEJ

          export APPTAINER_IMAGE
          cd "$apptainer_dir"
          ./chapel-quickstart.sh
          # Default config requires LLVM
          if [[ "$APPTAINER_IMAGE" != *"nollvm" ]]; then
              ./chapel-clean.sh
              ./chapel-default.sh
          fi

  arkouda-smoke-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      ARROW_VERSION: "19.0.1"
    timeout-minutes: 90 # usually takes ~45 minutes, double for safety
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: checkout Arkouda
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: Bears-R-Us/arkouda
        path: arkouda
        persist-credentials: false
    - name: apt install some Arkouda deps
      run: |
        apt update && apt install -y \
          libzmq3-dev \
          libcurl4-openssl-dev
    - name: set Arkouda env vars
      run: |
        cd arkouda
        {
          echo "ARKOUDA_URL=$(pwd)"
          echo "ARKOUDA_DEP_DIR=$(pwd)/dep"
          echo "ARKOUDA_SKIP_CHECK_DEPS=true"
          echo "ARKOUDA_SHA=$(git rev-parse HEAD)"
        } >> "$GITHUB_ENV"
    - name: cache Arkouda deps install
      id: cache-arkouda-deps
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #v6.1.0
      with:
        path: ${{ env.ARKOUDA_DEP_DIR }}
        key: arkouda-${{ env.ARKOUDA_SHA }}
    - name: install Arkouda deps (retrying)
      if: steps.cache-arkouda-deps.outputs.cache-hit != 'true'
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      with:
        max_attempts: 3
        timeout_seconds: 900
        retry_wait_seconds: 30
        on_retry_command: |
          cd arkouda
          git clean -dfx
        command: |
          num_procs=$(util/buildRelease/chpl-make-cpu_count)
          cd arkouda
          # Download sources serially first before building, as it is flaky and
          # that'll make it easier to diagnose failures.
          make deps-download-source
          make -j"$num_procs" install-deps
    - name: check contents of Arkouda deps install
      run: |
        test -d "$ARKOUDA_DEP_DIR"
        ls -R "$ARKOUDA_DEP_DIR"
    - name: build Chapel and run Arkouda smoke testing
      run: |
        source ./util/cron/common.bash
        source ./util/setchplenv.bash
        export CHPL_TEST_ARKOUDA_PERF=false
        source ./util/cron/common-arkouda.bash

        export NIGHTLY_TEST_SETTINGS=true
        export CHPL_SMOKE_SKIP_DOC=true
        export CHPL_SMOKE_SKIP_MAKE_MASON=true
        export ARKOUDA_SMOKE_TEST=true
        ./util/buildRelease/smokeTest
        make -j"$(util/buildRelease/chpl-make-cpu_count)" test-venv

        start_test test/studies/arkouda/

  test-make-install-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: run test-make-install-check.bash
      run: |
        ./util/cron/test-make-install-check.bash
