# Longest-running CI checks which should run less frequently, and need not be
# pre-merge. These are required for our full test coverage of Chapel.
name: Full CI checks

on:
  workflow_call:

permissions:
  contents: read
  packages: read

env:
  NIGHTLY_TEST_SETTINGS: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  trigger-failure:
    runs-on: ubuntu-slim
    steps:
      - run: exit 1
  also-trigger-failure:
    runs-on: ubuntu-slim
    steps:
      - name: break it
        run: exit 1

  arkouda-main-smoke-test:
    uses: ./.github/workflows/arkouda-smoke-test.yml
    with:
      arkouda-version: "main"

  test-make-install-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: run test-make-install-check.bash
      run: |
        ./util/cron/test-make-install-check.bash
