name: lint workflows

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  actionlint:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: .github
        persist-credentials: false
    - name: Download actionlint
      id: get_actionlint
      run: |
        wget https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
        echo "::add-matcher::./actionlint-matcher.json"
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      shell: bash
    - name: Check workflow files
      run: |
        ${STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE} -color
      shell: bash
      env:
        STEPS_GET_ACTIONLINT_OUTPUTS_EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}

  zizmor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: .github
        persist-credentials: false
    - name: Run zizmor
      uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
      with:
        advanced-security: false
        inputs: |
          .github/workflows

  # Canary for any linter failures
  linters-alert-failure:
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-slim
    needs:
      - actionlint
      - zizmor
    steps:
      - name: Fail
        run: |
          echo "A required status check has failed"
          exit 1
