name: CI Format Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 80 --exclude '(third-party/|test/)'"
          src: "."
          version: "24.4.0"
