name: CI Format Check

on: [push, pull_request, workflow_dispatch]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 80 --extend-exclude '^/(third-party|test|util/test|util/devel/test)/'"
          src: "."
      - uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 80 --extend-exclude '(install|build)/'"
          src: "third-party/chpl-venv"
