name: build release tarball

on:
  workflow_dispatch:
    inputs:
      chpl_version:
        type: string
        required: true

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  release-tarball:
    runs-on: ubuntu-latest
    env:
      CHPL_VERSION: ${{ inputs.chpl_version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: create release tarball
        run: |
          ./util/cron/create_release_tarball.bash
      - name: archive release tarball
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./tar/chapel-${{ env.CHPL_VERSION }}.tar.gz
          if-no-files-found: error
