name: ShellCheck

on: [push, pull_request, workflow_dispatch]

jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: error
          ignore_paths: ./test/* ./third-party/*
