name: ShellCheck

on: [push, pull_request, workflow_dispatch]

jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca
        with:
          severity: error
          ignore_paths: ./test/* ./third-party/*
