name: Test Chapel Language Server

on:
  workflow_dispatch:

jobs:
  test_chpl_language_server:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/chapel-github-ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - uses: actions/checkout@v4
    - name: test chpl-language-server
      run: |
        make test-chpl-language-server -j`util/buildRelease/chpl-make-cpu_count`
