# Kick off the full suite of checks post-merge and nightly.
name: Run full checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "30 0 * * *"
      timezone: "America/Vancouver"
  workflow_dispatch:

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  core-checks:
    uses: ./.github/workflows/core-ci-checks.yml

  extended-checks:
    uses: ./.github/workflows/extended-ci-checks.yml

  full-checks:
    uses: ./.github/workflows/full-ci-checks.yml

  send-failure-mail:
    if: cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')
    # if: github.event_name == 'schedule' && (cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
    runs-on: ubuntu-slim
    needs:
      - core-checks
      - extended-checks
      - full-checks
    steps:
      - name: gather info for email
        id: info
        run: |
          gh api /repos/chapel-lang/chapel/commits/${{ github.sha }} | tee commit.json
          gh api /repos/chapel-lang/chapel/actions/runs/${{ github.run_id }}/jobs | tee jobs.json

          {
            echo "date=$(date +'%Y-%m-%d')"
            echo "message=$(jq -r '.commit.message' commit.json | head -n 1)"
            echo "num_jobs=$(jq '.jobs | length' jobs.json)"
            echo "failed_jobs=$(jq '.jobs[] | select(.status != "completed" or .conclusion != "success" ) | .name' jobs.json)"
          } >> "$GITHUB_OUTPUT"
      - name: Send mail
        uses: dawidd6/action-send-mail@94de994a9f6fffee200243214e17002e2920bb59 # v18
        with:
           # Required mail server address if not connection_url:
           server_address: ${{ secrets.SMTP_PROVIDER }}
           server_port: 465
           secure: true
           username:  ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "[Chapel GA Tests] ${{ steps.info.outputs.date }}"
           to: "anna.rift@hpe.com"
           from:  "Chapel Automaton <chapel_commits@cray.com>"
           body: |
             One or more GitHub Actions jobs have failed:

             ---
             ${{ steps.info.outputs.failed_jobs }}
             ---

             Ran ${{ steps.info.outpus.num_jobs }} jobs at commit ${{ github.sha }}.
             > ${{ steps.info.outputs.message }}

             GitHub Actions run info:
             - SHA: ${{ github.sha }}
             - Run ID: ${{ github.run_id }}
             - Run attempt #: ${{ github.run_attempt }}
             - Run number: ${{ github.run_number }}
             - Triggering event name: ${{ github.event_name }}
