# This workflow is responsible for kicking off other workflows containing CI
# checks, as appropriate.
name: Trigger checks

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  core-checks:
    runs-on: ubuntu-slim
    steps:
    - uses: # other checks

  extended-checks:
    runs-on: ubuntu-slim
    env:
      EXTENDED_CHECKS_LABEL: "run extended CI checks"
    if: github.event_name == 'merge_group' || github.event_name == 'push' || (github.event_name == 'pull_request' && contains(github.event.*.labels.*.name, env.EXTENDED_CHECKS_LABEL))
    steps:
    - uses: # other checks

  # This job exists to have a single check for which failure means merging
  # should be blocked, for GH required status checks purposes.
  # - This is separate from merge queue requirements; these jobs will block even
  #   adding to the merge merge queue.
  # - Note that if a dependent job is _skipped_, it will
  #   not trigger failure of this job.
  checks-alert-failure:
    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-slim
    needs:
      - core-checks
      - extended-checks
    steps:
      - name: Fail
        run: |
          echo "A required status check has failed"
          exit 1
