# Kick off the full suite of checks post-merge and nightly.
name: Run full checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "30 0 * * *"
      timezone: "America/Vancouver"
  workflow_dispatch:

# Run serially per type of triggering event.
# Primarily intended to limit (avoid) concurrent runs for multiple PR merges in
# a row.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  queue: max

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  core-checks:
    uses: ./.github/workflows/core-ci-checks.yml

  extended-checks:
    uses: ./.github/workflows/extended-ci-checks.yml

  full-checks:
    uses: ./.github/workflows/full-ci-checks.yml

  send-failure-mail:
    if: cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')
    # if: github.event_name == 'schedule' && (cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure'))
    runs-on: ubuntu-slim
    needs:
      - core-checks
      - extended-checks
      - full-checks
    env:
      GH_TOKEN: ${{ github.token }}
      EMAIL_BODY_FILENAME: email.html
    steps:
      - name: determine date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name: generate fallback email body
        run: |
          cat << EOF > "$EMAIL_BODY_FILENAME"
          GitHub Actions nightly run failed, and an additional failure was
          encountered in generating a failure mail.

          Run ID: ${{ github.run_id }}
          EOF
      - name: generate email body
        run: |
          gh api /repos/chapel-lang/chapel/commits/${{ github.sha }} | tee commit.json
          gh api /repos/chapel-lang/chapel/actions/runs/${{ github.run_id }}/jobs | tee jobs.json

          message=$(jq -r '.commit.message' commit.json | head -n 1)
          num_jobs=$(jq '.jobs | length' jobs.json)
          readarray -t failed_job_ids < <(jq '.jobs[] | select(.status != "completed" or .conclusion == "success" ) | .id' jobs.json)

          failed_jobs_html=""
          for id in "${failed_job_ids[@]}"; do
            gh api "/repos/chapel-lang/chapel/actions/jobs/$id" > "job_$id.json"
            sleep 0.25
            failed_jobs_html+=$(jq -r '{html_url, name, first_bad_step: ([.steps[] | select(.conclusion != "success")] | first).name} | "<li><a href=\"\(.html_url)\">\(.name)</a>, step \(.first_bad_step)</li>"' "job_$id.json")
          done

          [[ $num_jobs -eq 1 ]] && plural="" || plural="s"

          cat << EOF > "$EMAIL_BODY_FILENAME"
          <h3>The following GitHub Actions job$plural failed:</h3>

          <ul>
          $failed_jobs_html
          </ul>

          <hr>

          <p>Ran $num_jobs total jobs at commit ${{ github.sha }} "$message".</p>

          <p>GitHub Actions run info:</p>
          <ul>
            <li>SHA: <a href="https://github.com/chapel-lang/chapel/commit/${{ github.sha }}">${{ github.sha }}</a></li>
            <li>Run ID: ${{ github.run_id }}</li>
            <li>Run attempt: <a href="https://github.com/chapel-lang/chapel/actions/runs/${{ github.run_attempt }}">${{ github.run_attempt }}</a></li>
            <li>Run number: ${{ github.run_number }}</li>
            <li>Triggering event name: ${{ github.event_name }}</li>
          </ul>
          EOF
      - name: print email body
        if: always()
        run: |
          cat "$EMAIL_BODY_FILENAME"
      - name: send mail
        if: always()
        uses: dawidd6/action-send-mail@94de994a9f6fffee200243214e17002e2920bb59 # v18
        with:
           # Required mail server address if not connection_url:
           server_address: ${{ secrets.SMTP_PROVIDER }}
           server_port: 465
           secure: true
           username:  ${{ secrets.MAIL_USERNAME }}
           password: ${{ secrets.MAIL_PASSWORD }}
           subject: "[Chapel GA Tests] ${{ steps.date.outputs.date }}"
           to: "anna.rift@hpe.com"
           from:  "Chapel Automaton <chapel_commits@cray.com>"
           html_body: file://${{ env.EMAIL_BODY_FILENAME }}
