VER = RV_EA_WB
GTM_CFLAGS += -DGTM_$(VER)

STM_SRCS = \
	stm-gtm.c \
	stm-gtm-desc.c \
	stm-gtm-memory.c \
	stm-gtm-$(VER).c \
	stm-gtm-cmgr.c \

SVN_SRCS = $(STM_SRCS)
SRCS = $(SVN_SRCS)

STM_OBJS = \
	$(STM_SRCS:%.c=$(STM_OBJDIR)/%.o) \
	$(STM_COMM_OBJS) 

RUNTIME_CFLAGS += $(GTM_CFLAGS) -I$(LIBATOMIC_INSTALL_DIR)/include
