var b: atomic bool;

b.read(memory_order_seq_cst);
b.write(true, memory_order_seq_cst);
b.exchange(true, memory_order_seq_cst);
b.compareExchange(true, false, memory_order_seq_cst);
b.compareExchangeWeak(false, true, memory_order_seq_cst);
b.compareExchangeStrong(true, false, memory_order_seq_cst);
b.testAndSet(memory_order_seq_cst);
b.clear(memory_order_seq_cst);
b.waitFor(false, memory_order_seq_cst);

var i: atomic int;
i.read(memory_order_seq_cst);
i.write(1, memory_order_seq_cst);
i.exchange(1, memory_order_seq_cst);
i.compareExchange(1, 2, memory_order_seq_cst);
i.compareExchangeWeak(2, 3, memory_order_seq_cst);
i.compareExchangeStrong(3, 4, memory_order_seq_cst);
i.fetchAdd(1, memory_order_seq_cst);
i.add(1, memory_order_seq_cst);
i.fetchSub(1, memory_order_seq_cst);
i.sub(1, memory_order_seq_cst);
i.fetchOr(1, memory_order_seq_cst);
i.or(1, memory_order_seq_cst);
i.fetchAnd(1, memory_order_seq_cst);
i.and(1, memory_order_seq_cst);
i.fetchXor(1, memory_order_seq_cst);
i.or(1, memory_order_seq_cst);
i.write(1, memory_order_seq_cst);
i.waitFor(1, memory_order_seq_cst);
